# 常用的库

In [1]:
import pandas as pd             #pandas引入dataframe数据类型，等效于excel的表形式
#https://pandas.pydata.org/     pandas文档
#https://www.pypandas.cn/       pandas中文文档

import numpy as np              #numpy主要实现运算
#https://numpy.org/             numpy文档
#https://www.numpy.org.cn/      numpy中文文档

import matplotlib.pyplot as plt #matplotlib主要实现画图相关功能
#https://matplotlib.org/        matplotlib文档
#http://www.matplotlib.org.cn/  matplotlib中文文档

%matplotlib inline


# 导入外部数据

In [2]:
#pd.read_X(read_csv,read_excel,read_table) 可以读入相应文件，支持csv，excel，txt文件类型等

df = pd.read_csv(r'/Users/kevin/Documents/财管部需求/德阳分行-黄河新区支行.csv'
                 #  ,sep = '[|][+][|]'
                   ,encoding = 'GBK'
                 #  ,header = None 
                #   ,skiprows =  
               #    ,delim_whitespace = True
                  ) 
#文件路径前最好加上r，防止字符转码，
#sep指定了以怎样的分隔符形式分割单元格，当分隔符为多个字符时则需正则表达式
#有时候读入显示中文乱码，可以指定encoding = 'GBK',默认则为utf-8
#header = None 表示不把第一行作为列名，当数据第一行不为列名时输入
#分隔符如果是若干个空格可以调整delim_whitespace参数为True
#read_excel时候参数sheet_name指定导入特定的工作表，默认为0指第一张工作表

In [3]:
df

,分级结果,归属行号,归属行名,归属二级行行号,归属一级行行号,客户号创建日期,创建柜员,创建机构号,创建机构名称,最后维护日期,...,出生日期,工作单位名称,工作单位行业类型,月收入,证件地址,手机号,居民涉税标识,签证类型,签证日期,是否在ACIF系统
0,A3,36010,中国银行德阳黄河新区支行,A2286,A0023,2011-11-18,234777.0,15055,中国银行德阳泰山北路支行,2017-07-22,...,100,100,100,100,100,100,100,100,100,N
1,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2018-08-14,9881900.0,36010,中国银行德阳黄河新区支行,2018-08-14,...,100,100,100,100,100,100,100,100,100,N
2,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2014-11-13,5366735.0,35922,中国银行德阳峨眉山南路支行,2016-11-15,...,100,100,100,100,100,100,100,100,100,N
3,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2012-04-10,5656324.0,15062,中国银行德阳庐山南路支行,2015-11-16,...,100,100,100,100,100,100,100,100,100,N
4,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-05-10,7072612.0,36010,中国银行德阳黄河新区支行,2019-05-10,...,100,100,100,100,100,100,100,100,100,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6766,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-01-10,9881900.0,36010,中国银行德阳黄河新区支行,2019-01-10,...,100,100,100,100,100,100,100,100,100,N
6767,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2017-12-07,6422733.0,36010,中国银行德阳黄河新区支行,2017-12-07,...,100,100,100,100,100,100,100,100,100,N
6768,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-03-25,9881200.0,15442,中国银行德阳罗江支行营业部,2019-03-25,...,100,100,100,100,100,100,100,100,100,N
6769,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-04-26,9881900.0,36010,中国银行德阳黄河新区支行,2019-04-26,...,100,100,100,100,100,100,100,100,100,N
6770,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2016-08-08,438782.0,35922,中国银行德阳峨眉山南路支行,2017-07-25,...,100,100,100,100,100,100,100,100,100,N

In [4]:
#数据显示不全时，可以调整pd.set_option里的相关参数

pd.set_option('display.max_rows', 1000,'display.max_columns', 1000,"display.max_colwidth", None,'display.width',None)

# 探查数据

In [5]:
#head函数查看数据表前若干行的数据，默认前五行

df.head()

,分级结果,归属行号,归属行名,归属二级行行号,归属一级行行号,客户号创建日期,创建柜员,创建机构号,创建机构名称,最后维护日期,最后维护柜员,报表日期,客户号,姓名,性别,国籍,常住地址,联系电话,证件类型,证件号码,证件有效期,职业,民族,出生日期,工作单位名称,工作单位行业类型,月收入,证件地址,手机号,居民涉税标识,签证类型,签证日期,是否在ACIF系统
0,A3,36010,中国银行德阳黄河新区支行,A2286,A0023,2011-11-18,234777.0,15055,中国银行德阳泰山北路支行,2017-07-22,9880100,2021-02-28,271251702,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
1,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2018-08-14,9881900.0,36010,中国银行德阳黄河新区支行,2018-08-14,9881000,2021-02-28,516976310,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
2,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2014-11-13,5366735.0,35922,中国银行德阳峨眉山南路支行,2016-11-15,9881900,2021-02-28,391831475,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
3,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2012-04-10,5656324.0,15062,中国银行德阳庐山南路支行,2015-11-16,9881000,2021-02-28,288367680,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
4,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-05-10,7072612.0,36010,中国银行德阳黄河新区支行,2019-05-10,7072612,2021-02-28,540339484,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N

In [6]:
#tail函数查看数据表前若干行的数据，默认倒数五行

df.tail(3)

,分级结果,归属行号,归属行名,归属二级行行号,归属一级行行号,客户号创建日期,创建柜员,创建机构号,创建机构名称,最后维护日期,最后维护柜员,报表日期,客户号,姓名,性别,国籍,常住地址,联系电话,证件类型,证件号码,证件有效期,职业,民族,出生日期,工作单位名称,工作单位行业类型,月收入,证件地址,手机号,居民涉税标识,签证类型,签证日期,是否在ACIF系统
6768,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-03-25,9881200.0,15442,中国银行德阳罗江支行营业部,2019-03-25,9881900,2021-02-28,536412969,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6769,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-04-26,9881900.0,36010,中国银行德阳黄河新区支行,2019-04-26,9958750,2021-02-28,539321779,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6770,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2016-08-08,438782.0,35922,中国银行德阳峨眉山南路支行,2017-07-25,9958750,2021-02-28,453369765,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N

### 数据纬度

In [7]:
#shape属性可以查看数据纬度，即多少行与多少列

df.shape

(6771, 33)

### 查看列名

In [8]:
#columns属性返回列名称

df.columns

Index(['分级结果', '归属行号', '归属行名', '归属二级行行号', '归属一级行行号', '客户号创建日期', '创建柜员',
       '创建机构号', '创建机构名称', '最后维护日期', '最后维护柜员', '报表日期', '客户号', '姓名', '性别', '国籍',
       '常住地址', '联系电话', '证件类型', '证件号码', '证件有效期', '职业', '民族', '出生日期', '工作单位名称',
       '工作单位行业类型', '月收入', '证件地址', '手机号', '居民涉税标识', '签证类型', '签证日期',
       '是否在ACIF系统 '],
      dtype='object')

In [9]:
df.index

RangeIndex(start=0, stop=6771, step=1)

### 数据表信息

In [10]:
#info函数查看数据表的整体信息，包括数据维度、列名称、数据格式和所占空间等信息。

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6771 entries, 0 to 6770
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   分级结果        6771 non-null   object
 1   归属行号        6771 non-null   int64
 2   归属行名        6771 non-null   object
 3   归属二级行行号     6771 non-null   object
 4   归属一级行行号     6771 non-null   object
 5   客户号创建日期     6771 non-null   object
 6   创建柜员        5224 non-null   float64
 7   创建机构号       6771 non-null   int64
 8   创建机构名称      6771 non-null   object
 9   最后维护日期      6771 non-null   object
 10  最后维护柜员      6771 non-null   int64
 11  报表日期        6771 non-null   object
 12  客户号         6771 non-null   int64
 13  姓名          6771 non-null   int64
 14  性别          6771 non-null   int64
 15  国籍          6771 non-null   int64
 16  常住地址        6771 non-null   int64
 17  联系电话        6771 non-null   int64
 18  证件类型        6771 non-null   int64
 19  证件号码        6771 non-null   int64
 20  证件有效期       6771 non-null   int64
 21  职业          6771 non-null   int64
 22  民族          6771 non-null   int64
 23  出生日期        6771 non-null   int64
 24  工作单位名称      6771 non-null   int64
 25  工作单位行业类型    6771 non-null   int64
 26  月收入         6771 non-null   int64
 27  证件地址        6771 non-null   int64
 28  手机号         6771 non-null   int64
 29  居民涉税标识      6771 non-null   int64
 30  签证类型        6771 non-null   int64
 31  签证日期        6771 non-null   int64
 32  是否在ACIF系统   6771 non-null   object
dtypes: float64(1), int64(23), object(9)
memory usage: 1.7+ MB

### 查看具体列

In [11]:
#查看单列课采取下列三种等效方式

df['国籍']    #返回序列
df[['国籍']].head()  #返回dataframe
df.iloc[:,15] #iloc函数，中括号右侧只能填数字，表示第几列，返回序列
df.iloc[:,[15]].head()    #iloc函数，中括号右侧只能填数字，表示第几列，返回dataframe
df.iloc[:,15:18] #返回连续若干列
df.loc[:,['国籍']].head()  #loc函数，中括号右侧只能填列名，左侧：冒号表示取所有行，也可加条件筛选个别行
df.loc[:,['国籍','证件号码']]#loc函数取若干列
df.loc[:,'国籍':'证件号码']  #取连续若干列

       国籍  常住地址  联系电话  证件类型  证件号码
0     100     1   100   100   100
1     100   100   100   100   100
2     100   100   100   100   100
3     100   100   100   100   100
4     100   100   100   100   100
...   ...   ...   ...   ...   ...
6766  100   100   100   100   100
6767  100   100   100   100   100
6768  100   100   100   100   100
6769  100   100   100   100   100
6770  100   100   100   100   100

[6771 rows x 5 columns]

In [12]:
df.iloc[:, df.columns.get_loc("国籍"):(df.columns.get_loc("国籍") + 3)]

       国籍  常住地址  联系电话
0     100     1   100
1     100   100   100
2     100   100   100
3     100   100   100
4     100   100   100
...   ...   ...   ...
6766  100   100   100
6767  100   100   100
6768  100   100   100
6769  100   100   100
6770  100   100   100

[6771 rows x 3 columns]

In [13]:
#查看多个列

df[['最后维护日期', '最后维护柜员']].head()

#也可创建一个对象专门存储所需取出的列：

SpecificColumnList = ['最后维护日期', '最后维护柜员']
df[SpecificColumnList].head()

       最后维护日期   最后维护柜员
0  2017-07-22  9880100
1  2018-08-14  9881000
2  2016-11-15  9881900
3  2015-11-16  9881000
4  2019-05-10  7072612

### 查看具体行数据

In [14]:
#loc函数可以取帮助取特定行

df[20:30]
df.loc[20:30]  #取21行到31行，注意python默认从0开始
df.loc[20:30, ['最后维护柜员','最后维护柜员']] #可同时限定所取的列

     最后维护柜员   最后维护柜员
20  8395067  8395067
21  9881000  9881000
22  9880100  9880100
23  7072612  7072612
24   234777   234777
25  9881000  9881000
26  9881900  9881900
27  9881000  9881000
28  9880100  9880100
29   234777   234777
30  9958750  9958750

In [15]:
df.iloc[20:30]

,分级结果,归属行号,归属行名,归属二级行行号,归属一级行行号,客户号创建日期,创建柜员,创建机构号,创建机构名称,最后维护日期,最后维护柜员,报表日期,客户号,姓名,性别,国籍,常住地址,联系电话,证件类型,证件号码,证件有效期,职业,民族,出生日期,工作单位名称,工作单位行业类型,月收入,证件地址,手机号,居民涉税标识,签证类型,签证日期,是否在ACIF系统
20,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2017-07-10,8395067.0,36010,中国银行德阳黄河新区支行,2017-07-12,8395067,2021-02-28,483179887,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
21,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2015-03-11,195840.0,35922,中国银行德阳峨眉山南路支行,2017-03-12,9881000,2021-02-28,405024189,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
22,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2018-06-28,630094.0,36010,中国银行德阳黄河新区支行,2018-06-28,9880100,2021-02-28,512796908,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
23,A3,36010,中国银行德阳黄河新区支行,A2286,A0023,2010-10-01,9995802.0,349,中国银行银行卡中心,2016-12-16,7072612,2021-02-28,81500835,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
24,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2018-09-03,234777.0,36010,中国银行德阳黄河新区支行,2018-09-03,234777,2021-02-28,518984861,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
25,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2012-08-03,8138894.0,15072,中国银行绵竹飞云街支行,2017-09-19,9881000,2021-02-28,300114074,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
26,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-03-18,630094.0,36010,中国银行德阳黄河新区支行,2019-03-18,9881900,2021-02-28,535681578,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
27,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-06-19,9881900.0,36010,中国银行德阳黄河新区支行,2019-06-19,9881000,2021-02-28,543587575,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
28,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2014-11-04,195840.0,35922,中国银行德阳峨眉山南路支行,2016-11-06,9880100,2021-02-28,390412225,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
29,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-02-07,234777.0,36010,中国银行德阳黄河新区支行,2019-02-07,234777,2021-02-28,532464962,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N

### 条件筛选

In [16]:
#可以添加筛选条件

df[df['创建机构名称'] == '中国银行德阳泰山北路支行'].tail(2)  # ==判断两个值是否相等，相等则为True，读出此行，反之False，忽略

,分级结果,归属行号,归属行名,归属二级行行号,归属一级行行号,客户号创建日期,创建柜员,创建机构号,创建机构名称,最后维护日期,最后维护柜员,报表日期,客户号,姓名,性别,国籍,常住地址,联系电话,证件类型,证件号码,证件有效期,职业,民族,出生日期,工作单位名称,工作单位行业类型,月收入,证件地址,手机号,居民涉税标识,签证类型,签证日期,是否在ACIF系统
6746,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2009-01-24,NaN,15055,中国银行德阳泰山北路支行,2017-08-30,9881900,2021-02-28,21241886,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6759,A2,36010,中国银行德阳黄河新区支行,A2286,A0023,2006-11-15,NaN,15055,中国银行德阳泰山北路支行,2017-08-10,7072612,2021-02-28,22987989,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,0,100,100,100,N

In [93]:
df['创建机构名称'] == '中国银行德阳泰山北路支行'

0        True
1       False
2       False
3       False
4       False
        ...
6766    False
6767    False
6768    False
6769    False
6770    False
Name: 创建机构名称, Length: 6771, dtype: bool

In [18]:
#多个筛选条件,每个条件需要括起来，&表示并，多个条件都需要同时满足

df[-(df['创建机构名称'] == '中国银行德阳泰山北路支行')& (df['分级结果'] == 'A3')]

     分级结果   归属行号          归属行名 归属二级行行号 归属一级行行号     客户号创建日期       创建柜员  创建机构号  \
5      A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-05-10  7072612.0  36010
23     A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2010-10-01  9995802.0    349
58     A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2016-11-23  2204665.0  35945
63     A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-07-20   630094.0  36010
67     A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-10-16  9881900.0  36010
72     A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-04-10  9881900.0  36010
79     A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-01-20   234777.0  36010
82     A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-05-27   630094.0  36010
90     A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2014-03-04  7739371.0  15437
100    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-10-07  9881900.0  36010
104    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2008-05-10        NaN  15056
109    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2010-03-23        NaN   3708
115    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2011-07-04  7739371.0  15063
117    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2007-02-20        NaN  15060
137    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-04-25  9881200.0    349
139    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2017-10-26  1302444.0  36010
142    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2008-11-09        NaN  15437
143    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2012-11-27  3618196.0  15062
152    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2008-09-19        NaN  15370
161    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-11-25  9881900.0  36010
174    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2009-06-12        NaN  15370
184    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-03-24  7072612.0  36010
185    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2009-12-19        NaN  15437
190    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2010-08-08  2627319.0  15061
193    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-10-11  9881900.0  36010
227    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-07-13  9881900.0  36010
237    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-09-28  9881200.0  36010
257    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2017-07-06  8395067.0  36010
268    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2014-01-22  9995802.0    349
274    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-08-06  9881900.0  36010
296    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2006-10-03        NaN  15060
297    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2020-01-06  9881900.0  36010
308    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-02-05  6422733.0  36010
320    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2011-03-16  1181565.0  15075
322    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-02-14  9881900.0  36010
326    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-07-27  9881200.0  36010
334    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-09-25   234777.0  36010
336    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2020-02-29  9881900.0  36010
350    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2017-12-13  6422733.0  36010
353    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-12-01  9881900.0  36010
358    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-05-17  9881900.0  36010
361    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-09-20  9881200.0  36010
371    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2003-10-24        NaN  13283
373    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2013-08-29  9995802.0    349
374    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-08-01  9881900.0  36010
379    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-08-12  9881200.0  15368
390    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2013-08-01  8859894.0  23547
391    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2005-04-03        NaN  15437
406    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2002-05-24        NaN  15074
408    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2010-04-23        NaN  15437
439    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2017-10-04  1302444.0  36010
443    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2002-05-24        NaN  15437
447    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2009-05-04        NaN   7196
462    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2016-06-08  2651618.0  14352
486    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2014-01-31  3495420.0  15439
489    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2011-09-25  8632148.0  15437
495    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-11-10  9881900.0  36010
496    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-01-13  6422733.0  36010
514    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-12-05  9881900.0  36010
516    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-03-23  7072612.0  36010
518    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2008-05-31        NaN  15086
523    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-06-25  9881200.0  36010
533    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-11-24  9881698.0  36010
537    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2011-11-14   973900.0  15095
546    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2016-12-06  9995802.0  15054
548    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2016-03-22  6927516.0   9248
557    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-06-27  8900834.0  36010
561    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-12-26  9881900.0  36010
562    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-06-28  9881900.0  36010
577    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2010-11-25  4666528.0  15087
584    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2016-07-09  5366735.0  35922
588    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-05-15  6422733.0  36010
598    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-11-30  9881900.0  36010
605    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-06-16  9881900.0  36010
608    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2017-06-27  8395067.0  36010
611    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-01-24  9881200.0  36010
616    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-09-29  9881900.0  36010
626    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-07-09  9881900.0  36010
628    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2009-12-02        NaN  15368
646    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-10-19  9881900.0  36010
651    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-05-18  9881900.0  36010
652    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2002-05-24        NaN  15087
653    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-11-01  9881900.0  36010
654    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2012-12-13  9995802.0    349
660    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2008-01-01        NaN  15072
662    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-07-19  9881900.0  36010
666    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2003-01-29        NaN  15056
680    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-12-03  9881900.0  36010
685    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-09-03   234777.0  36010
691    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2017-02-22  9995802.0  15054
696    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-09-03   234777.0  36010
704    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2007-05-13        NaN  15100
721    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-03-25  6422733.0  36010
722    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2014-08-27  9880800.0  17900
725    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-09-09  9881900.0  36010
732    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2009-02-25        NaN  15100
733    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-01-17  9881900.0  36010
736    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-02-03  9881900.0  36010
738    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-01-26  7072612.0  36010
739    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-07-11  9881900.0  36010
740    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-09-01  9881900.0  36010
755    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2017-02-14  1339119.0  36010
765    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2006-09-05        NaN  13381
768    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2020-01-11  9881900.0  36010
777    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-08-27  9881900.0  36010
805    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2006-01-13        NaN  15437
808    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2007-08-14        NaN  35922
809    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2015-07-17  9995802.0    349
819    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2002-05-24        NaN  15056
820    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2002-05-24        NaN  15061
825    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2010-06-25  1739417.0  15225
826    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2008-12-09        NaN  15404
834    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-09-18  9881900.0  36010
846    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-05-19  6422733.0  36010
853    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2013-07-26   677539.0  14339
854    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-10-24  9881900.0  36010
855    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2017-10-05  6422733.0  36010
865    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2017-08-05  1302444.0  36010
875    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-03-06  9881900.0  36010
888    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2011-04-15  9995802.0    349
891    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-05-04  9881900.0  36010
895    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2009-10-30        NaN  15370
930    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-09-03   234777.0  36010
937    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-05-28   630094.0  36010
942    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2010-05-04  6446463.0  15086
943    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-12-02  9881900.0  36010
952    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2020-01-07  9881900.0  36010
959    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-07-18  9881000.0  15075
965    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2011-04-22  5943807.0  15069
971    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2014-01-30  9995802.0    349
974    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-05-25   376171.0  36010
976    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-08-09  9881900.0  36010
980    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2017-11-30  7072612.0  36010
982    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-11-28  9881900.0  36010
984    A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2007-12-11        NaN  15437
1007   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2007-03-07        NaN  15087
1021   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2003-10-18        NaN  15061
1032   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-08-27  9881900.0  36010
1034   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-03-21  7072612.0  36010
1045   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2014-03-06  1862267.0  35922
1061   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-01-23  6422733.0  36010
1063   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-04-21  6422733.0  36010
1071   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-12-02  9881900.0  36010
1076   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-10-12  9881900.0  36010
1094   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2010-04-01        NaN   2189
1125   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2016-05-30  1594745.0  14974
1129   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-03-02  9881900.0  36010
1134   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-09-06  9881900.0  36010
1139   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-01-04  8900834.0  36010
1142   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-05-04  9881900.0  36010
1149   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-03-08  7072612.0  36010
1155   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2009-04-17        NaN  15437
1158   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-07-31  9881200.0  15368
1184   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-08-14  9881900.0  36010
1198   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-01-23  6422733.0  36010
1199   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-07-12  9881900.0  36010
1201   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-11-13  9881900.0  36010
1204   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2015-05-02  1039646.0  15084
1206   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2009-10-25        NaN  15398
1208   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-08-25  9881900.0  36010
1209   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2008-01-15        NaN  15437
1212   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-03-09  7072612.0  36010
1217   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2004-06-24        NaN   7872
1219   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-03-14  9881900.0  36010
1235   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-07-03  9881900.0  36010
1237   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2017-07-16  1302444.0  36010
1238   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-10-17  9881900.0  36010
1239   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2011-12-15  5112912.0  11154
1250   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2020-01-16  9881900.0  36010
1257   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2008-07-29        NaN  15426
1272   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-01-05   630094.0  36010
1281   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-11-09  9881900.0  36010
1296   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-08-19  9881900.0  36010
1306   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2017-07-20   234777.0  36010
1308   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-10-23   234777.0  36010
1309   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-06-27  9881900.0  36010
1312   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-04-07  6422733.0  36010
1317   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2011-04-19  3903205.0  15075
1329   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2013-01-15  6554631.0  12405
1331   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2009-06-29        NaN  15086
1336   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-02-12  7072612.0  36010
1338   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2008-01-22        NaN  15437
1340   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2011-11-09  2488219.0  15061
1344   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-10-18   234777.0  36010
1354   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2007-01-23        NaN  15084
1363   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2009-12-21        NaN  15061
1365   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-09-19  9881900.0  36010
1369   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2015-10-20  4953330.0  17388
1371   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-04-22  6422733.0  36010
1382   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-04-25  9881900.0  36010
1386   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-08-20   234777.0  36010
1387   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-01-18  9881900.0  36010
1389   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-03-29  9881200.0    349
1390   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-06-27  9881200.0    349
1410   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2017-02-23  9995802.0  36010
1422   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-02-14  8900834.0  36010
1435   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2008-12-10        NaN  15108
1446   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2009-06-22        NaN  13383
1452   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2017-07-06  8395067.0  36010
1454   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2011-04-06  4250771.0  15095
1478   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-08-05  6422733.0  36010
1485   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2007-09-03        NaN   9106
1491   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-09-30  9881900.0  36010
1494   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2013-09-26  5045522.0  13393
1495   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-05-22  9881900.0  36010
1501   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2010-02-04        NaN  15086
1505   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-08-13  9881900.0  36010
1512   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2014-01-30  9995802.0    349
1521   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2006-09-19        NaN  33749
1538   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-02-15  8900834.0  36010
1540   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2020-02-29  9881900.0  36010
1544   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-04-17  6422733.0  36010
1561   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-10-19  9881900.0  36010
1572   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2009-02-19        NaN  15090
1580   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2017-03-23  1302444.0  36010
1581   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2010-01-06        NaN  15075
1585   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-12-30  9881900.0  36010
1586   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-12-31  9881900.0  36010
1593   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2009-11-02        NaN  15060
1598   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2013-07-22  7769973.0  27025
1602   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-03-14  9958751.0  15437
1607   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2010-08-11  9995802.0    349
1610   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-10-16   234777.0  36010
1614   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2014-05-08  8978322.0  35894
1615   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-08-09  9881200.0  36010
1622   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-12-06  9881900.0  36010
1625   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2012-08-06  4936697.0  15541
1637   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2009-08-22        NaN  15087
1653   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2017-05-04  1302444.0  36010
1672   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2007-07-23        NaN  15087
1677   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-04-22  6422733.0  36010
1678   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2007-01-09        NaN  15086
1681   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2007-02-15        NaN  15087
1685   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-05-28   630094.0  36010
1692   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-05-08  7072612.0  36010
1708   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2007-11-22        NaN  35945
1721   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2008-03-23        NaN  15442
1741   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2016-04-07   970305.0  15087
1749   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2017-04-14  9995802.0  36010
1758   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-05-05   376171.0  36010
1775   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-03-14  6422733.0  36010
1776   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2019-06-07  9881900.0  36010
1777   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-10-23  9881200.0  15368
1784   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2017-03-19  8395067.0  36010
1785   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2013-02-21  2522368.0  15123
1794   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2011-04-05  6846165.0  15067
1798   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2012-09-03  2643041.0  17527
1815   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-08-16  9881200.0  36010
1820   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2012-03-03    60027.0  14927
1821   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2008-10-21        NaN  14916
1824   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2010-02-10        NaN  15060
1833   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2009-07-03        NaN  15437
1845   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2009-07-18        NaN  15060
1849   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2018-04-10  6422733.0  36010
1860   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2013-04-01  2490079.0   6642
1864   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2015-08-27  1788848.0  15084
1868   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2010-11-26  9995802.0    349
1875   A3  36010  中国银行德阳黄河新区支行   A2286   A0023  2013-08-22  9995802.0    349

In [19]:
#  | 表示或者，条件满足其一即可，可在条件前加-，表示取其补集

df[-(df['创建机构名称'] != '中国银行德阳泰山北路支行') | (df['分级结果'] == 'A3')]

,分级结果,归属行号,归属行名,归属二级行行号,归属一级行行号,客户号创建日期,创建柜员,创建机构号,创建机构名称,最后维护日期,最后维护柜员,报表日期,客户号,姓名,性别,国籍,常住地址,联系电话,证件类型,证件号码,证件有效期,职业,民族,出生日期,工作单位名称,工作单位行业类型,月收入,证件地址,手机号,居民涉税标识,签证类型,签证日期,是否在ACIF系统
0,A3,36010,中国银行德阳黄河新区支行,A2286,A0023,2011-11-18,234777.0,15055,中国银行德阳泰山北路支行,2017-07-22,9880100,2021-02-28,271251702,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
5,A3,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-05-10,7072612.0,36010,中国银行德阳黄河新区支行,2019-05-10,9881900,2021-02-28,540356218,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
23,A3,36010,中国银行德阳黄河新区支行,A2286,A0023,2010-10-01,9995802.0,349,中国银行银行卡中心,2016-12-16,7072612,2021-02-28,81500835,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
58,A3,36010,中国银行德阳黄河新区支行,A2286,A0023,2016-11-23,2204665.0,35945,中国银行德阳岷山路支行,2017-02-02,1302444,2021-02-28,463562552,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
63,A3,36010,中国银行德阳黄河新区支行,A2286,A0023,2018-07-20,630094.0,36010,中国银行德阳黄河新区支行,2018-07-20,87505,2021-02-28,514546241,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6751,A3,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-09-10,9881900.0,36010,中国银行德阳黄河新区支行,2019-09-10,9881900,2021-02-28,551546949,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6753,A3,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-05-24,9881900.0,36010,中国银行德阳黄河新区支行,2019-05-24,9881900,2021-02-28,541478994,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6756,A3,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-01-19,9881900.0,36010,中国银行德阳黄河新区支行,2019-01-19,9881000,2021-02-28,531212895,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6759,A2,36010,中国银行德阳黄河新区支行,A2286,A0023,2006-11-15,NaN,15055,中国银行德阳泰山北路支行,2017-08-10,7072612,2021-02-28,22987989,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,0,100,100,100,N
6763,A3,36010,中国银行德阳黄河新区支行,A2286,A0023,2006-08-09,NaN,15437,中国银行德阳分行营业部,2015-08-25,9881900,2021-02-28,22838898,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N

In [20]:
#可以创建对象，满足特殊值的要求

SpecificValuesList = ['中国银行德阳泰山北路支行','中国银行德阳黄河新区支行']
df[df['创建机构名称'].isin(SpecificValuesList)]

,分级结果,归属行号,归属行名,归属二级行行号,归属一级行行号,客户号创建日期,创建柜员,创建机构号,创建机构名称,最后维护日期,最后维护柜员,报表日期,客户号,姓名,性别,国籍,常住地址,联系电话,证件类型,证件号码,证件有效期,职业,民族,出生日期,工作单位名称,工作单位行业类型,月收入,证件地址,手机号,居民涉税标识,签证类型,签证日期,是否在ACIF系统
0,A3,36010,中国银行德阳黄河新区支行,A2286,A0023,2011-11-18,234777.0,15055,中国银行德阳泰山北路支行,2017-07-22,9880100,2021-02-28,271251702,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
1,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2018-08-14,9881900.0,36010,中国银行德阳黄河新区支行,2018-08-14,9881000,2021-02-28,516976310,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
4,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-05-10,7072612.0,36010,中国银行德阳黄河新区支行,2019-05-10,7072612,2021-02-28,540339484,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
5,A3,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-05-10,7072612.0,36010,中国银行德阳黄河新区支行,2019-05-10,9881900,2021-02-28,540356218,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-12-30,9881900.0,36010,中国银行德阳黄河新区支行,2019-12-30,9881900,2021-02-28,561037947,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6760,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2020-03-30,6819299.0,36010,中国银行德阳黄河新区支行,2020-03-30,6819299,2021-02-28,565307034,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6761,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2020-01-02,7072612.0,36010,中国银行德阳黄河新区支行,2020-01-02,7072612,2021-02-28,561223684,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6766,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-01-10,9881900.0,36010,中国银行德阳黄河新区支行,2019-01-10,9881900,2021-02-28,530409314,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6767,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2017-12-07,6422733.0,36010,中国银行德阳黄河新区支行,2017-12-07,6422733,2021-02-28,496339576,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6769,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-04-26,9881900.0,36010,中国银行德阳黄河新区支行,2019-04-26,9958750,2021-02-28,539321779,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N

### 数据格式

In [21]:
#dtypes属性查看数据表各列格式

df.dtypes

分级结果           object
归属行号            int64
归属行名           object
归属二级行行号        object
归属一级行行号        object
客户号创建日期        object
创建柜员          float64
创建机构号           int64
创建机构名称         object
最后维护日期         object
最后维护柜员          int64
报表日期           object
客户号             int64
姓名              int64
性别              int64
国籍              int64
常住地址            int64
联系电话            int64
证件类型            int64
证件号码            int64
证件有效期           int64
职业              int64
民族              int64
出生日期            int64
工作单位名称          int64
工作单位行业类型        int64
月收入             int64
证件地址            int64
手机号             int64
居民涉税标识          int64
签证类型            int64
签证日期            int64
是否在ACIF系统      object
dtype: object

In [22]:
#查看单列的格式

df['姓名'].dtype

dtype('int64')

### 描述统计

In [23]:
#describe函数描述统计

df.describe(include = 'all').T    #include默认为none，如果设定为all,则连会对所有列都进行统计

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
分级结果,6771,10,A1,5583,NaN,NaN,NaN,NaN,NaN,NaN,NaN
归属行号,6771.0,NaN,NaN,NaN,36010.0,0.0,36010.0,36010.0,36010.0,36010.0,36010.0
归属行名,6771,1,中国银行德阳黄河新区支行,6771,NaN,NaN,NaN,NaN,NaN,NaN,NaN
归属二级行行号,6771,1,A2286,6771,NaN,NaN,NaN,NaN,NaN,NaN,NaN
归属一级行行号,6771,1,A0023,6771,NaN,NaN,NaN,NaN,NaN,NaN,NaN
客户号创建日期,6771,3061,2002-05-24,105,NaN,NaN,NaN,NaN,NaN,NaN,NaN
创建柜员,5224.0,NaN,NaN,NaN,6718932.165199,3539373.082847,42953.0,3618196.0,8015034.5,9881900.0,9995802.0
创建机构号,6771.0,NaN,NaN,NaN,25788.582041,11342.291597,349.0,15084.0,36010.0,36010.0,50030.0
创建机构名称,6771,641,中国银行德阳黄河新区支行,3448,NaN,NaN,NaN,NaN,NaN,NaN,NaN
最后维护日期,6771,1904,2010-05-02,419,NaN,NaN,NaN,NaN,NaN,NaN,NaN
最后维护柜员,6771.0,NaN,NaN,NaN,8437545.355634,2940904.807513,0.0,8675159.0,9881000.0,9881900.0,9999001.0
报表日期,6771,1,2021-02-28,6771,NaN,NaN,NaN,NaN,NaN,NaN,NaN
客户号,6771.0,NaN,NaN,NaN,358413182.674937,209308108.610666,4162478.0,112238355.5,480024429.0,524748794.0,565410007.0
姓名,6771.0,NaN,NaN,NaN,100.0,0.0,100.0,100.0,100.0,100.0,100.0
性别,6771.0,NaN,NaN,NaN,100.0,0.0,100.0,100.0,100.0,100.0,100.0
国籍,6771.0,NaN,NaN,NaN,100.0,0.0,100.0,100.0,100.0,100.0,100.0
常住地址,6771.0,NaN,NaN,NaN,87.513218,32.870363,0.0,100.0,100.0,100.0,100.0
联系电话,6771.0,NaN,NaN,NaN,99.867523,3.631557,0.0,100.0,100.0,100.0,100.0
证件类型,6771.0,NaN,NaN,NaN,97.814208,14.623034,0.0,100.0,100.0,100.0,100.0
证件号码,6771.0,NaN,NaN,NaN,99.985379,1.20312,1.0,100.0,100.0,100.0,100.0
证件有效期,6771.0,NaN,NaN,NaN,99.262147,8.5553,0.0,100.0,100.0,100.0,100.0
职业,6771.0,NaN,NaN,NaN,99.645547,5.943472,0.0,100.0,100.0,100.0,100.0
民族,6771.0,NaN,NaN,NaN,99.527396,6.858861,0.0,100.0,100.0,100.0,100.0
出生日期,6771.0,NaN,NaN,NaN,100.0,0.0,100.0,100.0,100.0,100.0,100.0
工作单位名称,6771.0,NaN,NaN,NaN,98.725742,11.169949,0.0,100.0,100.0,100.0,100.0
工作单位行业类型,6771.0,NaN,NaN,NaN,100.0,0.0,100.0,100.0,100.0,100.0,100.0
月收入,6771.0,NaN,NaN,NaN,99.868409,3.607225,1.0,100.0,100.0,100.0,100.0
证件地址,6771.0,NaN,NaN,NaN,99.118594,9.322483,0.0,100.0,100.0,100.0,100.0
手机号,6771.0,NaN,NaN,NaN,98.892483,10.4655,0.0,100.0,100.0,100.0,100.0
居民涉税标识,6771.0,NaN,NaN,NaN,99.985231,1.215272,0.0,100.0,100.0,100.0,100.0
签证类型,6771.0,NaN,NaN,NaN,99.985231,1.215272,0.0,100.0,100.0,100.0,100.0
签证日期,6771.0,NaN,NaN,NaN,100.0,0.0,100.0,100.0,100.0,100.0,100.0
是否在ACIF系统,6771,2,N,6720,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 检查空值

In [24]:
#isnull函数检查表中数据是否为空值

df.isnull().sum()

分级结果             0
归属行号             0
归属行名             0
归属二级行行号          0
归属一级行行号          0
客户号创建日期          0
创建柜员          1547
创建机构号            0
创建机构名称           0
最后维护日期           0
最后维护柜员           0
报表日期             0
客户号              0
姓名               0
性别               0
国籍               0
常住地址             0
联系电话             0
证件类型             0
证件号码             0
证件有效期            0
职业               0
民族               0
出生日期             0
工作单位名称           0
工作单位行业类型         0
月收入              0
证件地址             0
手机号              0
居民涉税标识           0
签证类型             0
签证日期             0
是否在ACIF系统        0
dtype: int64

In [25]:
df.isnull()

,分级结果,归属行号,归属行名,归属二级行行号,归属一级行行号,客户号创建日期,创建柜员,创建机构号,创建机构名称,最后维护日期,最后维护柜员,报表日期,客户号,姓名,性别,国籍,常住地址,联系电话,证件类型,证件号码,证件有效期,职业,民族,出生日期,工作单位名称,工作单位行业类型,月收入,证件地址,手机号,居民涉税标识,签证类型,签证日期,是否在ACIF系统
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6766,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6767,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6768,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6769,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6770,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [26]:
#查看具体某列为空的记录

df[df['创建柜员'].isnull()]

,分级结果,归属行号,归属行名,归属二级行行号,归属一级行行号,客户号创建日期,创建柜员,创建机构号,创建机构名称,最后维护日期,最后维护柜员,报表日期,客户号,姓名,性别,国籍,常住地址,联系电话,证件类型,证件号码,证件有效期,职业,民族,出生日期,工作单位名称,工作单位行业类型,月收入,证件地址,手机号,居民涉税标识,签证类型,签证日期,是否在ACIF系统
7,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2008-06-03,NaN,2086,中国银行北京东直门支行,2012-01-15,9881000,2021-02-28,96624196,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
16,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2008-02-14,NaN,15437,中国银行德阳分行营业部,2017-07-20,9881900,2021-02-28,19319337,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
30,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2010-01-01,NaN,15370,中国银行四川省分行支付清算部,2015-12-03,9958750,2021-02-28,30819741,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
34,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2010-02-22,NaN,15442,中国银行德阳罗江支行营业部,2016-09-11,9881900,2021-02-28,20960683,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
35,A2,36010,中国银行德阳黄河新区支行,A2286,A0023,2009-08-27,NaN,15442,中国银行德阳罗江支行营业部,2017-01-04,1604515,2021-02-28,18268495,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,0,100,100,100,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6746,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2009-01-24,NaN,15055,中国银行德阳泰山北路支行,2017-08-30,9881900,2021-02-28,21241886,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6749,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2002-05-24,NaN,15072,中国银行绵竹飞云街支行,2016-11-08,8002823,2021-02-28,19601646,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6759,A2,36010,中国银行德阳黄河新区支行,A2286,A0023,2006-11-15,NaN,15055,中国银行德阳泰山北路支行,2017-08-10,7072612,2021-02-28,22987989,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,0,100,100,100,N
6762,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2006-07-30,NaN,15086,中国银行德阳钟鼓楼支行,2016-11-25,938427,2021-02-28,22825365,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6763,A3,36010,中国银行德阳黄河新区支行,A2286,A0023,2006-08-09,NaN,15437,中国银行德阳分行营业部,2015-08-25,9881900,2021-02-28,22838898,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N

In [27]:
df['创建柜员'].isnull()

0       False
1       False
2       False
3       False
4       False
        ...
6766    False
6767    False
6768    False
6769    False
6770    False
Name: 创建柜员, Length: 6771, dtype: bool

### 检查唯一值

In [28]:
#unique函数查看某列的唯一值

df['手机号'].unique()

array([100,   0,   1])

In [29]:
#values属性查看数据表的值

df.values

array([['A3', 36010, '中国银行德阳黄河新区支行', ..., 100, 100, 'N '],
       ['A1', 36010, '中国银行德阳黄河新区支行', ..., 100, 100, 'N '],
       ['A1', 36010, '中国银行德阳黄河新区支行', ..., 100, 100, 'N '],
       ...,
       ['A1', 36010, '中国银行德阳黄河新区支行', ..., 100, 100, 'N '],
       ['A1', 36010, '中国银行德阳黄河新区支行', ..., 100, 100, 'N '],
       ['A1', 36010, '中国银行德阳黄河新区支行', ..., 100, 100, 'N ']], dtype=object)

### 排序

In [30]:
df.sort_values(by = ['分级结果','归属行号']
              #,inplace = True
              #,ascending= False
              #,na_position='first'  
              )

,分级结果,归属行号,归属行名,归属二级行行号,归属一级行行号,客户号创建日期,创建柜员,创建机构号,创建机构名称,最后维护日期,最后维护柜员,报表日期,客户号,姓名,性别,国籍,常住地址,联系电话,证件类型,证件号码,证件有效期,职业,民族,出生日期,工作单位名称,工作单位行业类型,月收入,证件地址,手机号,居民涉税标识,签证类型,签证日期,是否在ACIF系统
1,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2018-08-14,9881900.0,36010,中国银行德阳黄河新区支行,2018-08-14,9881000,2021-02-28,516976310,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
2,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2014-11-13,5366735.0,35922,中国银行德阳峨眉山南路支行,2016-11-15,9881900,2021-02-28,391831475,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
3,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2012-04-10,5656324.0,15062,中国银行德阳庐山南路支行,2015-11-16,9881000,2021-02-28,288367680,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
4,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-05-10,7072612.0,36010,中国银行德阳黄河新区支行,2019-05-10,7072612,2021-02-28,540339484,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-12-30,9881900.0,36010,中国银行德阳黄河新区支行,2019-12-30,9881900,2021-02-28,561037947,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6672,C,36010,中国银行德阳黄河新区支行,A2286,A0023,2018-04-29,6422733.0,36010,中国银行德阳黄河新区支行,2018-04-29,9881000,2021-02-28,508357373,100,100,100,100,100,0,100,100,100,100,100,100,100,100,100,100,100,100,100,Y
6674,C,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-09-28,9881900.0,36010,中国银行德阳黄河新区支行,2019-09-28,9881900,2021-02-28,553244665,100,100,100,100,100,0,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6680,C,36010,中国银行德阳黄河新区支行,A2286,A0023,2018-02-26,6422733.0,36010,中国银行德阳黄河新区支行,2018-02-26,6422733,2021-02-28,502955651,100,100,100,100,100,0,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6714,C,36010,中国银行德阳黄河新区支行,A2286,A0023,2011-03-02,82439.0,15079,中国银行什邡亭江西路支行,2011-03-02,9881900,2021-02-28,111710799,100,100,100,100,100,0,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6715,C,36010,中国银行德阳黄河新区支行,A2286,A0023,2017-09-03,8395067.0,36010,中国银行德阳黄河新区支行,2017-09-05,8395067,2021-02-28,488093002,100,100,100,100,100,0,100,100,100,100,100,100,100,100,100,100,100,100,100,N

In [31]:
df.sort_values(by = ['分级结果','最后维护日期'])[['分级结果','最后维护日期']]

     分级结果      最后维护日期
2111   A1  2010-04-24
3745   A1  2010-04-24
5533   A1  2010-04-24
6169   A1  2010-04-24
52     A1  2010-05-02
...   ...         ...
5509    C  2019-12-01
5563    C  2019-12-15
5725    C  2020-01-06
3406    C  2020-01-17
277     C  2020-03-19

[6771 rows x 2 columns]

In [32]:
df.sort_values(by = ['最后维护日期', '分级结果'])[['分级结果','最后维护日期']]

     分级结果      最后维护日期
2111   A1  2010-04-24
3745   A1  2010-04-24
5533   A1  2010-04-24
6169   A1  2010-04-24
3814   A2  2010-04-24
...   ...         ...
3448   A1  2020-03-30
4049   A1  2020-03-30
4830   A1  2020-03-30
6760   A1  2020-03-30
389    A1  2020-03-31

[6771 rows x 2 columns]

In [33]:
#对不同列采取不同排序策略

df.sort_values(by = ['分级结果', '最后维护日期'] ,ascending = [True, False])[['分级结果','最后维护日期']]

     分级结果      最后维护日期
389    A1  2020-03-31
2327   A1  2020-03-30
2775   A1  2020-03-30
2943   A1  2020-03-30
3448   A1  2020-03-30
...   ...         ...
2607    C  2011-10-01
6714    C  2011-03-02
3334    C  2010-09-01
1325    C  2010-05-02
3513    C  2010-05-02

[6771 rows x 2 columns]

# 数据清理

### 处理空值(删除或填充)

In [34]:
#dropna函数删除数据表中含有空值的行

df.dropna(how='any'
        #  ,inplace = True
         )    
#how为any，则某行有一个列值为空则删除此行，how为all，则全行为空才删除
#inplace默认为False，设置为True才对原表数据进行修改

,分级结果,归属行号,归属行名,归属二级行行号,归属一级行行号,客户号创建日期,创建柜员,创建机构号,创建机构名称,最后维护日期,最后维护柜员,报表日期,客户号,姓名,性别,国籍,常住地址,联系电话,证件类型,证件号码,证件有效期,职业,民族,出生日期,工作单位名称,工作单位行业类型,月收入,证件地址,手机号,居民涉税标识,签证类型,签证日期,是否在ACIF系统
0,A3,36010,中国银行德阳黄河新区支行,A2286,A0023,2011-11-18,234777.0,15055,中国银行德阳泰山北路支行,2017-07-22,9880100,2021-02-28,271251702,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
1,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2018-08-14,9881900.0,36010,中国银行德阳黄河新区支行,2018-08-14,9881000,2021-02-28,516976310,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
2,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2014-11-13,5366735.0,35922,中国银行德阳峨眉山南路支行,2016-11-15,9881900,2021-02-28,391831475,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
3,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2012-04-10,5656324.0,15062,中国银行德阳庐山南路支行,2015-11-16,9881000,2021-02-28,288367680,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
4,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-05-10,7072612.0,36010,中国银行德阳黄河新区支行,2019-05-10,7072612,2021-02-28,540339484,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6766,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-01-10,9881900.0,36010,中国银行德阳黄河新区支行,2019-01-10,9881900,2021-02-28,530409314,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6767,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2017-12-07,6422733.0,36010,中国银行德阳黄河新区支行,2017-12-07,6422733,2021-02-28,496339576,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6768,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-03-25,9881200.0,15442,中国银行德阳罗江支行营业部,2019-03-25,9881900,2021-02-28,536412969,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6769,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-04-26,9881900.0,36010,中国银行德阳黄河新区支行,2019-04-26,9958750,2021-02-28,539321779,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6770,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2016-08-08,438782.0,35922,中国银行德阳峨眉山南路支行,2017-07-25,9958750,2021-02-28,453369765,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N

In [35]:
#使用数字0填充数据表中的空值

df.fillna(value=0
         #,inplace = True
         )

,分级结果,归属行号,归属行名,归属二级行行号,归属一级行行号,客户号创建日期,创建柜员,创建机构号,创建机构名称,最后维护日期,最后维护柜员,报表日期,客户号,姓名,性别,国籍,常住地址,联系电话,证件类型,证件号码,证件有效期,职业,民族,出生日期,工作单位名称,工作单位行业类型,月收入,证件地址,手机号,居民涉税标识,签证类型,签证日期,是否在ACIF系统
0,A3,36010,中国银行德阳黄河新区支行,A2286,A0023,2011-11-18,234777.0,15055,中国银行德阳泰山北路支行,2017-07-22,9880100,2021-02-28,271251702,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
1,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2018-08-14,9881900.0,36010,中国银行德阳黄河新区支行,2018-08-14,9881000,2021-02-28,516976310,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
2,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2014-11-13,5366735.0,35922,中国银行德阳峨眉山南路支行,2016-11-15,9881900,2021-02-28,391831475,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
3,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2012-04-10,5656324.0,15062,中国银行德阳庐山南路支行,2015-11-16,9881000,2021-02-28,288367680,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
4,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-05-10,7072612.0,36010,中国银行德阳黄河新区支行,2019-05-10,7072612,2021-02-28,540339484,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6766,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-01-10,9881900.0,36010,中国银行德阳黄河新区支行,2019-01-10,9881900,2021-02-28,530409314,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6767,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2017-12-07,6422733.0,36010,中国银行德阳黄河新区支行,2017-12-07,6422733,2021-02-28,496339576,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6768,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-03-25,9881200.0,15442,中国银行德阳罗江支行营业部,2019-03-25,9881900,2021-02-28,536412969,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6769,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-04-26,9881900.0,36010,中国银行德阳黄河新区支行,2019-04-26,9958750,2021-02-28,539321779,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6770,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2016-08-08,438782.0,35922,中国银行德阳峨眉山南路支行,2017-07-25,9958750,2021-02-28,453369765,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N

In [36]:
#使用price列的均值填充price列的空值

df['创建柜员'].fillna(df['创建柜员'].mean()
                  #,inplace = True
                 )

0        234777.0
1       9881900.0
2       5366735.0
3       5656324.0
4       7072612.0
          ...
6766    9881900.0
6767    6422733.0
6768    9881200.0
6769    9881900.0
6770     438782.0
Name: 创建柜员, Length: 6771, dtype: float64

In [37]:
df['创建柜员'].mean()

6718932.165199081

### 清理空格

In [38]:
#str.strip(), str.lstrip(), str.rstrip(), str.replace

a = '  3   21  '
str.strip(a)
a.strip()

'3   21'

In [91]:
#清除city列中的字符空格 
#map vs. apply : map作用于series，支持f和dick-like; apply还可作用于dataframe,作用于df时，对整行整列进行操作，通过axis控制轴向

df['创建机构名称'] = df['创建机构名称'].map(str.strip)

### 大小写转换

In [40]:
#str.lower函数可以使大写字母变小写,str.upper函数可以使小写变大写

df['分级结果']=df['分级结果'].str.upper()
df

,分级结果,归属行号,归属行名,归属二级行行号,归属一级行行号,客户号创建日期,创建柜员,创建机构号,创建机构名称,最后维护日期,最后维护柜员,报表日期,客户号,姓名,性别,国籍,常住地址,联系电话,证件类型,证件号码,证件有效期,职业,民族,出生日期,工作单位名称,工作单位行业类型,月收入,证件地址,手机号,居民涉税标识,签证类型,签证日期,是否在ACIF系统
0,A3,36010,中国银行德阳黄河新区支行,A2286,A0023,2011-11-18,234777.0,15055,中国银行德阳泰山北路支行,2017-07-22,9880100,2021-02-28,271251702,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
1,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2018-08-14,9881900.0,36010,中国银行德阳黄河新区支行,2018-08-14,9881000,2021-02-28,516976310,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
2,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2014-11-13,5366735.0,35922,中国银行德阳峨眉山南路支行,2016-11-15,9881900,2021-02-28,391831475,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
3,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2012-04-10,5656324.0,15062,中国银行德阳庐山南路支行,2015-11-16,9881000,2021-02-28,288367680,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
4,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-05-10,7072612.0,36010,中国银行德阳黄河新区支行,2019-05-10,7072612,2021-02-28,540339484,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6766,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-01-10,9881900.0,36010,中国银行德阳黄河新区支行,2019-01-10,9881900,2021-02-28,530409314,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6767,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2017-12-07,6422733.0,36010,中国银行德阳黄河新区支行,2017-12-07,6422733,2021-02-28,496339576,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6768,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-03-25,9881200.0,15442,中国银行德阳罗江支行营业部,2019-03-25,9881900,2021-02-28,536412969,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6769,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-04-26,9881900.0,36010,中国银行德阳黄河新区支行,2019-04-26,9958750,2021-02-28,539321779,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6770,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2016-08-08,438782.0,35922,中国银行德阳峨眉山南路支行,2017-07-25,9958750,2021-02-28,453369765,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N

### 更改数据类型

In [41]:
#astype函数来修改数据格式

df['客户号'] = df['客户号'].astype('string') #此处指定为整数型,还可指定为float浮点数，object/str字符串，category类别变量
df.dtypes

分级结果           object
归属行号            int64
归属行名           object
归属二级行行号        object
归属一级行行号        object
客户号创建日期        object
创建柜员          float64
创建机构号           int64
创建机构名称         object
最后维护日期         object
最后维护柜员          int64
报表日期           object
客户号            string
姓名              int64
性别              int64
国籍              int64
常住地址            int64
联系电话            int64
证件类型            int64
证件号码            int64
证件有效期           int64
职业              int64
民族              int64
出生日期            int64
工作单位名称          int64
工作单位行业类型        int64
月收入             int64
证件地址            int64
手机号             int64
居民涉税标识          int64
签证类型            int64
签证日期            int64
是否在ACIF系统      object
dtype: object

In [42]:
#可用pa.to_datetime来转化列为日期类型

df[['客户号创建日期','最后维护日期','报表日期']] = df[['客户号创建日期','最后维护日期','报表日期']].apply(pd.to_datetime)

In [43]:
df[['客户号创建日期','最后维护日期','报表日期']].dtypes

客户号创建日期    datetime64[ns]
最后维护日期     datetime64[ns]
报表日期       datetime64[ns]
dtype: object

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6771 entries, 0 to 6770
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   分级结果        6771 non-null   object
 1   归属行号        6771 non-null   int64
 2   归属行名        6771 non-null   object
 3   归属二级行行号     6771 non-null   object
 4   归属一级行行号     6771 non-null   object
 5   客户号创建日期     6771 non-null   datetime64[ns]
 6   创建柜员        5224 non-null   float64
 7   创建机构号       6771 non-null   int64
 8   创建机构名称      6771 non-null   object
 9   最后维护日期      6771 non-null   datetime64[ns]
 10  最后维护柜员      6771 non-null   int64
 11  报表日期        6771 non-null   datetime64[ns]
 12  客户号         6771 non-null   string
 13  姓名          6771 non-null   int64
 14  性别          6771 non-null   int64
 15  国籍          6771 non-null   int64
 16  常住地址        6771 non-null   int64
 17  联系电话        6771 non-null   int64
 18  证件类型        6771 non-null   int64
 19  证件号码        6771 non-null   int64
 20  证件有效期       6771 non-null   int64
 21  职业          6771 non-null   int64
 22  民族          6771 non-null   int64
 23  出生日期        6771 non-null   int64
 24  工作单位名称      6771 non-null   int64
 25  工作单位行业类型    6771 non-null   int64
 26  月收入         6771 non-null   int64
 27  证件地址        6771 non-null   int64
 28  手机号         6771 non-null   int64
 29  居民涉税标识      6771 non-null   int64
 30  签证类型        6771 non-null   int64
 31  签证日期        6771 non-null   int64
 32  是否在ACIF系统   6771 non-null   object
dtypes: datetime64[ns](3), float64(1), int64(22), object(6), string(1)
memory usage: 1.7+ MB

### 修改列名

In [45]:
#将列名old修改为new，可以通过映射同时改变多个列的列名

df.rename(columns={'姓名':'名字'}
        #  ,inplace = True
         )

,分级结果,归属行号,归属行名,归属二级行行号,归属一级行行号,客户号创建日期,创建柜员,创建机构号,创建机构名称,最后维护日期,最后维护柜员,报表日期,客户号,名字,性别,国籍,常住地址,联系电话,证件类型,证件号码,证件有效期,职业,民族,出生日期,工作单位名称,工作单位行业类型,月收入,证件地址,手机号,居民涉税标识,签证类型,签证日期,是否在ACIF系统
0,A3,36010,中国银行德阳黄河新区支行,A2286,A0023,2011-11-18,234777.0,15055,中国银行德阳泰山北路支行,2017-07-22,9880100,2021-02-28,271251702,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
1,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2018-08-14,9881900.0,36010,中国银行德阳黄河新区支行,2018-08-14,9881000,2021-02-28,516976310,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
2,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2014-11-13,5366735.0,35922,中国银行德阳峨眉山南路支行,2016-11-15,9881900,2021-02-28,391831475,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
3,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2012-04-10,5656324.0,15062,中国银行德阳庐山南路支行,2015-11-16,9881000,2021-02-28,288367680,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
4,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-05-10,7072612.0,36010,中国银行德阳黄河新区支行,2019-05-10,7072612,2021-02-28,540339484,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6766,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-01-10,9881900.0,36010,中国银行德阳黄河新区支行,2019-01-10,9881900,2021-02-28,530409314,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6767,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2017-12-07,6422733.0,36010,中国银行德阳黄河新区支行,2017-12-07,6422733,2021-02-28,496339576,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6768,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-03-25,9881200.0,15442,中国银行德阳罗江支行营业部,2019-03-25,9881900,2021-02-28,536412969,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6769,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-04-26,9881900.0,36010,中国银行德阳黄河新区支行,2019-04-26,9958750,2021-02-28,539321779,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6770,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2016-08-08,438782.0,35922,中国银行德阳峨眉山南路支行,2017-07-25,9958750,2021-02-28,453369765,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N

In [46]:
df.rename(columns={'姓名':'名字','地址':'住址','电话号码':'号码'}
        # ,inplace = True
         ) 
df

,分级结果,归属行号,归属行名,归属二级行行号,归属一级行行号,客户号创建日期,创建柜员,创建机构号,创建机构名称,最后维护日期,最后维护柜员,报表日期,客户号,姓名,性别,国籍,常住地址,联系电话,证件类型,证件号码,证件有效期,职业,民族,出生日期,工作单位名称,工作单位行业类型,月收入,证件地址,手机号,居民涉税标识,签证类型,签证日期,是否在ACIF系统
0,A3,36010,中国银行德阳黄河新区支行,A2286,A0023,2011-11-18,234777.0,15055,中国银行德阳泰山北路支行,2017-07-22,9880100,2021-02-28,271251702,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
1,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2018-08-14,9881900.0,36010,中国银行德阳黄河新区支行,2018-08-14,9881000,2021-02-28,516976310,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
2,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2014-11-13,5366735.0,35922,中国银行德阳峨眉山南路支行,2016-11-15,9881900,2021-02-28,391831475,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
3,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2012-04-10,5656324.0,15062,中国银行德阳庐山南路支行,2015-11-16,9881000,2021-02-28,288367680,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
4,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-05-10,7072612.0,36010,中国银行德阳黄河新区支行,2019-05-10,7072612,2021-02-28,540339484,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6766,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-01-10,9881900.0,36010,中国银行德阳黄河新区支行,2019-01-10,9881900,2021-02-28,530409314,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6767,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2017-12-07,6422733.0,36010,中国银行德阳黄河新区支行,2017-12-07,6422733,2021-02-28,496339576,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6768,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-03-25,9881200.0,15442,中国银行德阳罗江支行营业部,2019-03-25,9881900,2021-02-28,536412969,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6769,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-04-26,9881900.0,36010,中国银行德阳黄河新区支行,2019-04-26,9958750,2021-02-28,539321779,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6770,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2016-08-08,438782.0,35922,中国银行德阳峨眉山南路支行,2017-07-25,9958750,2021-02-28,453369765,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N

In [47]:
#df.columns = []

### 删除重复项

In [48]:
#将city列中的重复值删除，默认保留第一个出现的

df['分级结果'].drop_duplicates(#inplace = True
                  )

0       A3
1       A1
13      A4
31       C
35      A2
125     B5
247     B1
1190    B2
1218    B4
2124    B3
Name: 分级结果, dtype: object

In [49]:
#将city列中的重复值删除，默认保留最后一个

df['分级结果'].drop_duplicates(keep='last'
                           #,inplace = True
                          )

4324    B4
6195    B3
6565    A4
6605    B5
6618    B1
6715     C
6717    B2
6759    A2
6763    A3
6770    A1
Name: 分级结果, dtype: object

### 删除特定行

In [50]:
#drop函数中可以添加条件实现对特定行删除

df.drop(df[df['最后维护柜员'] == '9881000'].index
          #  ,inplace = True
            )
df

,分级结果,归属行号,归属行名,归属二级行行号,归属一级行行号,客户号创建日期,创建柜员,创建机构号,创建机构名称,最后维护日期,最后维护柜员,报表日期,客户号,姓名,性别,国籍,常住地址,联系电话,证件类型,证件号码,证件有效期,职业,民族,出生日期,工作单位名称,工作单位行业类型,月收入,证件地址,手机号,居民涉税标识,签证类型,签证日期,是否在ACIF系统
0,A3,36010,中国银行德阳黄河新区支行,A2286,A0023,2011-11-18,234777.0,15055,中国银行德阳泰山北路支行,2017-07-22,9880100,2021-02-28,271251702,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
1,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2018-08-14,9881900.0,36010,中国银行德阳黄河新区支行,2018-08-14,9881000,2021-02-28,516976310,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
2,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2014-11-13,5366735.0,35922,中国银行德阳峨眉山南路支行,2016-11-15,9881900,2021-02-28,391831475,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
3,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2012-04-10,5656324.0,15062,中国银行德阳庐山南路支行,2015-11-16,9881000,2021-02-28,288367680,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
4,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-05-10,7072612.0,36010,中国银行德阳黄河新区支行,2019-05-10,7072612,2021-02-28,540339484,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6766,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-01-10,9881900.0,36010,中国银行德阳黄河新区支行,2019-01-10,9881900,2021-02-28,530409314,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6767,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2017-12-07,6422733.0,36010,中国银行德阳黄河新区支行,2017-12-07,6422733,2021-02-28,496339576,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6768,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-03-25,9881200.0,15442,中国银行德阳罗江支行营业部,2019-03-25,9881900,2021-02-28,536412969,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6769,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-04-26,9881900.0,36010,中国银行德阳黄河新区支行,2019-04-26,9958750,2021-02-28,539321779,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6770,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2016-08-08,438782.0,35922,中国银行德阳峨眉山南路支行,2017-07-25,9958750,2021-02-28,453369765,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N

In [51]:
df.drop(0)

,分级结果,归属行号,归属行名,归属二级行行号,归属一级行行号,客户号创建日期,创建柜员,创建机构号,创建机构名称,最后维护日期,最后维护柜员,报表日期,客户号,姓名,性别,国籍,常住地址,联系电话,证件类型,证件号码,证件有效期,职业,民族,出生日期,工作单位名称,工作单位行业类型,月收入,证件地址,手机号,居民涉税标识,签证类型,签证日期,是否在ACIF系统
1,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2018-08-14,9881900.0,36010,中国银行德阳黄河新区支行,2018-08-14,9881000,2021-02-28,516976310,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
2,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2014-11-13,5366735.0,35922,中国银行德阳峨眉山南路支行,2016-11-15,9881900,2021-02-28,391831475,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
3,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2012-04-10,5656324.0,15062,中国银行德阳庐山南路支行,2015-11-16,9881000,2021-02-28,288367680,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
4,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-05-10,7072612.0,36010,中国银行德阳黄河新区支行,2019-05-10,7072612,2021-02-28,540339484,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
5,A3,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-05-10,7072612.0,36010,中国银行德阳黄河新区支行,2019-05-10,9881900,2021-02-28,540356218,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6766,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-01-10,9881900.0,36010,中国银行德阳黄河新区支行,2019-01-10,9881900,2021-02-28,530409314,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6767,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2017-12-07,6422733.0,36010,中国银行德阳黄河新区支行,2017-12-07,6422733,2021-02-28,496339576,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6768,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-03-25,9881200.0,15442,中国银行德阳罗江支行营业部,2019-03-25,9881900,2021-02-28,536412969,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6769,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-04-26,9881900.0,36010,中国银行德阳黄河新区支行,2019-04-26,9958750,2021-02-28,539321779,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6770,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2016-08-08,438782.0,35922,中国银行德阳峨眉山南路支行,2017-07-25,9958750,2021-02-28,453369765,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N

### 删除特定列

In [52]:
df.drop(['工作单位名称','工作单位行业类型']
        ,axis = 1
  #     ,inplace = True
       )

,分级结果,归属行号,归属行名,归属二级行行号,归属一级行行号,客户号创建日期,创建柜员,创建机构号,创建机构名称,最后维护日期,最后维护柜员,报表日期,客户号,姓名,性别,国籍,常住地址,联系电话,证件类型,证件号码,证件有效期,职业,民族,出生日期,月收入,证件地址,手机号,居民涉税标识,签证类型,签证日期,是否在ACIF系统
0,A3,36010,中国银行德阳黄河新区支行,A2286,A0023,2011-11-18,234777.0,15055,中国银行德阳泰山北路支行,2017-07-22,9880100,2021-02-28,271251702,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,N
1,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2018-08-14,9881900.0,36010,中国银行德阳黄河新区支行,2018-08-14,9881000,2021-02-28,516976310,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
2,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2014-11-13,5366735.0,35922,中国银行德阳峨眉山南路支行,2016-11-15,9881900,2021-02-28,391831475,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
3,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2012-04-10,5656324.0,15062,中国银行德阳庐山南路支行,2015-11-16,9881000,2021-02-28,288367680,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
4,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-05-10,7072612.0,36010,中国银行德阳黄河新区支行,2019-05-10,7072612,2021-02-28,540339484,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6766,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-01-10,9881900.0,36010,中国银行德阳黄河新区支行,2019-01-10,9881900,2021-02-28,530409314,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6767,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2017-12-07,6422733.0,36010,中国银行德阳黄河新区支行,2017-12-07,6422733,2021-02-28,496339576,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6768,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-03-25,9881200.0,15442,中国银行德阳罗江支行营业部,2019-03-25,9881900,2021-02-28,536412969,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6769,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-04-26,9881900.0,36010,中国银行德阳黄河新区支行,2019-04-26,9958750,2021-02-28,539321779,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6770,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2016-08-08,438782.0,35922,中国银行德阳峨眉山南路支行,2017-07-25,9958750,2021-02-28,453369765,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N

In [53]:
df.drop(columns = ['工作单位名称','工作单位行业类型'])

,分级结果,归属行号,归属行名,归属二级行行号,归属一级行行号,客户号创建日期,创建柜员,创建机构号,创建机构名称,最后维护日期,最后维护柜员,报表日期,客户号,姓名,性别,国籍,常住地址,联系电话,证件类型,证件号码,证件有效期,职业,民族,出生日期,月收入,证件地址,手机号,居民涉税标识,签证类型,签证日期,是否在ACIF系统
0,A3,36010,中国银行德阳黄河新区支行,A2286,A0023,2011-11-18,234777.0,15055,中国银行德阳泰山北路支行,2017-07-22,9880100,2021-02-28,271251702,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,N
1,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2018-08-14,9881900.0,36010,中国银行德阳黄河新区支行,2018-08-14,9881000,2021-02-28,516976310,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
2,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2014-11-13,5366735.0,35922,中国银行德阳峨眉山南路支行,2016-11-15,9881900,2021-02-28,391831475,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
3,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2012-04-10,5656324.0,15062,中国银行德阳庐山南路支行,2015-11-16,9881000,2021-02-28,288367680,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
4,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-05-10,7072612.0,36010,中国银行德阳黄河新区支行,2019-05-10,7072612,2021-02-28,540339484,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6766,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-01-10,9881900.0,36010,中国银行德阳黄河新区支行,2019-01-10,9881900,2021-02-28,530409314,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6767,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2017-12-07,6422733.0,36010,中国银行德阳黄河新区支行,2017-12-07,6422733,2021-02-28,496339576,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6768,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-03-25,9881200.0,15442,中国银行德阳罗江支行营业部,2019-03-25,9881900,2021-02-28,536412969,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6769,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-04-26,9881900.0,36010,中国银行德阳黄河新区支行,2019-04-26,9958750,2021-02-28,539321779,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
6770,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2016-08-08,438782.0,35922,中国银行德阳峨眉山南路支行,2017-07-25,9958750,2021-02-28,453369765,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N

### 数值修改及替换

In [54]:
#将city列出现的old值替换为new

df['归属二级行行号'].replace('A2286','11111'
                    # ,inplace = True
                     ) 

#对于替换多个不同的值，可以写成{'old1':'new1','old2':'new2','old3':'new3'……}的映射形式

0       11111
1       11111
2       11111
3       11111
4       11111
        ...
6766    11111
6767    11111
6768    11111
6769    11111
6770    11111
Name: 归属二级行行号, Length: 6771, dtype: object

### 创建新的列

In [55]:
#创建新的列

df['年收入'] = df['月收入'] * 12
# df['报表时年龄'] = df['报表日期'] - df['出生日期']

### 模糊匹配

In [56]:
df['客户号'].dtype

StringDtype

In [57]:
#str.startswith查询以某个字符开始

df[df['客户号'].str.startswith('9')]  #查询客户号以9开头的记录

,分级结果,归属行号,归属行名,归属二级行行号,归属一级行行号,客户号创建日期,创建柜员,创建机构号,创建机构名称,最后维护日期,最后维护柜员,报表日期,客户号,姓名,性别,国籍,常住地址,联系电话,证件类型,证件号码,证件有效期,职业,民族,出生日期,工作单位名称,工作单位行业类型,月收入,证件地址,手机号,居民涉税标识,签证类型,签证日期,是否在ACIF系统,年收入
7,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2008-06-03,NaN,2086,中国银行北京东直门支行,2012-01-15,9881000,2021-02-28,96624196,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
586,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2009-08-24,NaN,2200,中国银行北京怀柔府前街支行,2010-10-06,9881900,2021-02-28,99246136,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
1154,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2008-11-05,NaN,20141,中国银行北京广渠东路支行,2017-08-22,7072612,2021-02-28,99628636,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
1320,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2007-07-20,NaN,16181,中国银行西安师大路支行,2016-05-20,9881900,2021-02-28,9613858,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
2447,C,36010,中国银行德阳黄河新区支行,A2286,A0023,2008-07-30,NaN,4881,中国银行沈阳开发区支行营业部,2013-04-04,6422733,2021-02-28,91433725,100,100,100,100,100,0,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
4142,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2005-11-11,NaN,4648,中国银行丹东江城大街支行,2017-01-28,234777,2021-02-28,92574187,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
4373,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2009-10-29,NaN,2051,中国银行北京大北窑支行,2016-02-17,9881900,2021-02-28,95808296,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
4441,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2007-12-07,NaN,2104,中国银行北京文慧园支行,2010-10-06,9881200,2021-02-28,99448087,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
4624,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2008-02-09,NaN,2079,中国银行北京将台路支行,2016-08-20,9881000,2021-02-28,98770339,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
5343,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2004-11-11,NaN,2085,中国银行北京发展大厦支行,2010-10-06,9881000,2021-02-28,96618736,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
6195,B3,36010,中国银行德阳黄河新区支行,A2286,A0023,2005-07-22,NaN,16140,中国银行西安翠华路支行,2017-08-29,9881900,2021-02-28,9037710,100,100,100,100,100,100,100,100,0,100,100,100,100,100,100,100,100,100,100,N,1200

In [58]:
#endswith查询以某个字符结尾

df[df['客户号'].str.endswith('9')]  #查询客户号以9结尾的记录

     分级结果   归属行号          归属行名 归属二级行行号 归属一级行行号    客户号创建日期       创建柜员  创建机构号  \
10     A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2014-11-24  2682871.0  15090
21     A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2015-03-11   195840.0  35922
47     A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2011-02-19  9995802.0    349
52     A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2008-08-05        NaN  15061
66     A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2013-03-14  8002823.0  15056
78     A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2011-09-25  2960808.0  15087
79     A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-01-20   234777.0  36010
87     A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2010-03-17        NaN  15243
88     A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2008-11-15        NaN  15090
96     A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-05-30  1302444.0  36010
108    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-02-25  6422733.0  36010
133    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2006-07-26        NaN  15442
139    A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-10-26  1302444.0  36010
140    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2006-02-14        NaN  15439
145    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2008-11-06        NaN  15439
148    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-12-07  9958751.0  15437
154    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2011-05-07  2601160.0  15060
162    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2011-04-28  3268223.0  15035
174    A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2009-06-12        NaN  15370
182    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-06-19   630094.0  36010
183    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2008-10-26        NaN  15087
191    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2009-11-06        NaN  15370
198    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2015-10-07  2073014.0  15437
199    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-07-10  9881900.0  36010
207    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2015-02-09  3517078.0  35922
209    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2010-07-12  2677020.0  15437
212    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-12-14  8900834.0  36010
218    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-05-07  8395067.0  36010
242    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-03-06  1302444.0  36010
245    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-08-19  9881200.0  36010
258    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2007-12-19        NaN  15087
273    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-01-21   234777.0  36010
275    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-10-24  6422733.0  36010
291     C  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-03-07   234777.0  36010
295    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2011-04-12  9995802.0    349
322    A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-02-14  9881900.0  36010
335    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-03-21  9881900.0  36010
338    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2012-05-16  2066664.0  15063
342    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2020-01-17  9881900.0  36010
360    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2013-07-30   317586.0   5995
365    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-09-08  9881900.0  36010
375    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2014-07-12  3360704.0  15086
377    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-03-13  1302444.0  36010
382    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2016-03-08  5186491.0  15437
385    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-09-25   234777.0  36010
399    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2010-11-26  2488219.0  15061
407    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2009-01-21        NaN  15437
421    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-09-03   234777.0  36010
440    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2011-11-14  7020520.0  35809
456    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-09-09  9881900.0  36010
461    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2014-11-09  8233492.0  11037
481    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2020-01-11  9881900.0  36010
483    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2002-11-02        NaN  15069
486    A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2014-01-31  3495420.0  15439
492    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-09-25  9881900.0  36010
500    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2004-08-14        NaN  17756
501    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2011-05-12  9991600.0  15437
504    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2020-03-14  7451497.0  15437
519    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2010-08-27  7384970.0  15055
524    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-01-23  6422733.0  36010
533    A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-11-24  9881698.0  36010
536    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2016-11-15  8799016.0  35934
537    A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2011-11-14   973900.0  15095
553    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-03-21  9881900.0  36010
557    A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-06-27  8900834.0  36010
589    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-09-23  9995802.0  36010
590    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-07-07  8395067.0  36010
599    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-10-04  1302444.0  36010
604    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-11-26  9881900.0  36010
615    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2013-12-27  8361644.0  15075
624    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-10-26  9881900.0  36010
625    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2009-10-30        NaN  15370
644    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2010-05-22  6995197.0  15437
655    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2009-07-25        NaN  15087
662    A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-07-19  9881900.0  36010
664    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2013-01-08  9991600.0  15437
666    A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2003-01-29        NaN  15056
680    A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-12-03  9881900.0  36010
681    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2010-03-12        NaN  15061
682    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-12-14  2590056.0  15437
705    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-05-08  9881900.0  36010
708    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-07-02  9881900.0  36010
717    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-01-18   630094.0  36010
724    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-03-09  9881900.0  36010
727    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-08-11  9881900.0  36010
736    A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-02-03  9881900.0  36010
757    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-12-17  9881900.0  36010
759    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-09-02  9881900.0  36010
766    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2016-04-05  6309891.0  15086
769     C  36010  中国银行德阳黄河新区支行   A2286   A0023 2016-03-22  1453240.0  15063
791    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-12-01  9881900.0  36010
815    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-08-21  9881900.0  36010
826    A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2008-12-09        NaN  15404
831    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-09-12   234777.0  36010
847    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2015-03-17  4065115.0  15082
857    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2010-08-13  7596717.0  15291
865    A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-08-05  1302444.0  36010
870    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-12-17  9881900.0  36010
878    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-06-23  1302444.0  36010
894    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2009-10-10        NaN  15370
899     C  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-01-31   234777.0  36010
916    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2014-11-22   208726.0  35922
917    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2009-11-26        NaN  15062
918    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-05-07  9881900.0  36010
921    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2010-08-22  6880884.0  15075
922    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2015-06-23   195840.0  35922
924    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2007-07-22        NaN  15060
932    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2008-02-03        NaN  15437
937    A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-05-28   630094.0  36010
939    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-12-15  8900834.0  36010
941    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2009-04-28        NaN  15060
952    A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2020-01-07  9881900.0  36010
973    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-09-14  9881900.0  36010
974    A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-05-25   376171.0  36010
976    A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-08-09  9881900.0  36010
991    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-09-21  8395067.0  36010
999    A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-10-01  9881900.0  36010
1003   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-08-22  9881900.0  36010
1008   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-07-14  9881900.0  36010
1017   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-07-31  9881900.0  36010
1018   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2020-03-18  9881900.0  36010
1027   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-09-08  9881900.0  36010
1043   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2015-03-20  5453697.0  15063
1044   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-10-29  9881900.0  36010
1057   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2016-04-21  2812733.0  35945
1062   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-05-14  6422733.0  36010
1073   A2  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-04-19  7072612.0  36010
1096   B5  36010  中国银行德阳黄河新区支行   A2286   A0023 2020-02-06  9881000.0  36010
1113   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2007-12-21        NaN   2877
1122   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2006-09-12        NaN  17414
1131   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2013-02-01  7711668.0  14960
1174   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2020-03-08  9881900.0  36010
1188   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2012-08-08  2090678.0  15442
1206   A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2009-10-25        NaN  15398
1221   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2014-12-22  8361644.0  15075
1225   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-12-08   630094.0  36010
1227   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-02-08  9881900.0  15015
1229   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2009-09-18        NaN  15370
1233   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2009-06-04        NaN  15062
1248    C  36010  中国银行德阳黄河新区支行   A2286   A0023 2013-10-11  3401257.0  13717
1291   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-03-28  9881900.0  36010
1303   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2015-07-21   208726.0  15061
1306   A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-07-20   234777.0  36010
1312   A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-04-07  6422733.0  36010
1332   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2008-10-30        NaN  15060
1337   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-12-20  7072612.0  36010
1338   A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2008-01-22        NaN  15437
1350   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-03-18   234777.0  36010
1372   B1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-11-27  9995802.0  36010
1412   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-04-16  1302444.0  36010
1413   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2012-03-11  2960808.0  15055
1414   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2014-12-16  1760194.0  15062
1435   A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2008-12-10        NaN  15108
1449   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2009-04-09        NaN  15060
1459   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-11-25  7072612.0  36010
1462   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-11-05  9881900.0  36010
1466   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-09-18  9881900.0  36010
1467   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2012-11-21  1364367.0  17177
1489   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-03-18   630094.0  36010
1491   A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-09-30  9881900.0  36010
1510   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-05-19  9881900.0  36010
1522   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2008-12-29        NaN  15060
1538   A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-02-15  8900834.0  36010
1539   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-07-03  1302444.0  36010
1557   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-01-21   234777.0  36010
1566   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-03-01  6422733.0  36010
1578   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2009-11-30        NaN  15370
1585   A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-12-30  9881900.0  36010
1586   A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-12-31  9881900.0  36010
1587   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2016-02-18  4951137.0  15084
1591   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2011-11-18   234777.0  15055
1592   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2009-10-29        NaN  15055
1594   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2015-10-08  7447541.0  15055
1603   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-03-18   630094.0  36010
1610   A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-10-16   234777.0  36010
1611   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2003-04-15        NaN  14940
1613   B1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-06-17  9995802.0  36010
1617   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-09-11  9881900.0  36010
1622   A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-12-06  9881900.0  36010
1632   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-11-21  9881900.0  36010
1636   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-11-21  9881900.0  36010
1653   A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-05-04  1302444.0  36010
1674   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2020-03-20  9881900.0  36010
1680   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-08-21   234777.0  36010
1684   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-01-23   376171.0  36010
1692   A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-05-08  7072612.0  36010
1696   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-06-06  9881900.0  36010
1699   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-06-11  9881900.0  36010
1709   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-06-03  9881900.0  36010
1720   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2009-11-04        NaN  15074
1722   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2020-03-18  9881900.0  36010
1727   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-04-22   234777.0  36010
1749   A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-04-14  9995802.0  36010
1751   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2005-04-02        NaN  15087
1760   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2008-08-10        NaN  15087
1762   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2010-06-08  8221653.0  15437
1770   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-09-20  9995802.0  36010
1771   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-04-04  5754707.0  36010
1788    C  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-08-31  9881900.0  36010
1789    C  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-02-09  1302444.0  36010
1790   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2009-11-18        NaN  15368
1804   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-09-07  9881900.0  36010
1828   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2009-06-23        NaN  15055
1870   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-09-25   234777.0  36010
1878   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-09-07  9881900.0  36010
1884   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2008-04-02        NaN  15055
1885   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-07-09  9881900.0  36010
1892   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-01-10  8900834.0  36010
1911   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-05-29  9881900.0  17731
1912   A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-09-03   234777.0  36010
1913   A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2006-09-21        NaN  27114
1930   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2007-10-22        NaN  15440
1937   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2010-01-28        NaN  15060
1954   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-03-28  9880700.0  15437
1961   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2009-03-13        NaN  15437
1971   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2013-02-28  2362888.0  15086
1991   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-11-30  6422733.0  36010
2014   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2002-05-24        NaN  14904
2020   A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-07-25  9881900.0  36010
2025   A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-05-09  9881900.0  36010
2031   A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-02-03  9881900.0  36010
2042   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-11-10  6422733.0  36010
2058   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2010-11-10  5253818.0   2126
2084    C  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-02-01  1302444.0  36010
2092   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-02-10  3622024.0  15432
2098   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2010-04-07        NaN  15084
2104   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2014-10-22  2677020.0  15086
2105   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-11-10  9881900.0  36010
2108   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2007-03-13        NaN   7180
2111   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2004-04-23        NaN  16374
2112   A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2009-02-08        NaN  15087
2138   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2010-01-04        NaN  15370
2142   A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2011-08-31  9991600.0  15437
2155   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-12-02  9881900.0  36010
2181   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2011-04-29  1254870.0  15241
2189   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-01-16  6422733.0  36010
2191   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2010-05-20  3165501.0  15056
2197   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-07-30  9881900.0  36010
2219   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-02-23  9881900.0  36010
2228   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-04-13   234777.0  36010
2229    C  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-10-31  7072612.0  36010
2238   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2020-03-01  9881900.0  36010
2249   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2007-09-28        NaN  15055
2264   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-04-24   234777.0  36010
2306   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2015-02-15  2090678.0  15090
2307   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-09-05  9881900.0  36010
2328   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2003-03-11        NaN  15437
2334   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-10-03  1302444.0  36010
2346   A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2007-04-21        NaN   7880
2351   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-04-24  9881900.0  36010
2365   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2011-01-31  7318642.0  15055
2383   A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2012-09-18  1538680.0  35945
2390   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2009-09-02        NaN  15061
2415   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-06-04  9881900.0  36010
2429   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-05-26  9995802.0  36010
2433   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2017-05-04  9995802.0  36010
2438   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2011-05-12  9991600.0  15437
2446   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2019-09-11  9881900.0  36010
2468   A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2018-10-27  9881900.0  36010
2473   A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2006-04-08        NaN  35922
2474   A1  36010  中国银行德阳黄河新区支行   A2286   A0023 2012-12-25  8702325.0  33902
2476   A3  36010  中国银行德阳黄河新区支行   A2286   A0023 2011-01-06  7863240.0  15437

In [59]:
#contains查询包含某个字符

df[df['客户号'].str.contains('999')]  #查询客户号包含999的记录

,分级结果,归属行号,归属行名,归属二级行行号,归属一级行行号,客户号创建日期,创建柜员,创建机构号,创建机构名称,最后维护日期,最后维护柜员,报表日期,客户号,姓名,性别,国籍,常住地址,联系电话,证件类型,证件号码,证件有效期,职业,民族,出生日期,工作单位名称,工作单位行业类型,月收入,证件地址,手机号,居民涉税标识,签证类型,签证日期,是否在ACIF系统,年收入
199,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2018-07-10,9881900.0,36010,中国银行德阳黄河新区支行,2018-07-10,9881000,2021-02-28,513718999,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
573,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2012-05-09,8632148.0,15437,中国银行德阳分行营业部,2012-05-09,7598692,2021-02-28,290999865,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
615,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2013-12-27,8361644.0,15075,中国银行德阳黄河东路支行,2013-12-27,9881900,2021-02-28,359064999,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
949,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2009-12-18,NaN,15077,中国银行什邡金河路支行,2016-12-01,1302444,2021-02-28,19992267,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
1083,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2018-01-18,6422733.0,36010,中国银行德阳黄河新区支行,2018-01-18,9881000,2021-02-28,499983195,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
1206,A3,36010,中国银行德阳黄河新区支行,A2286,A0023,2009-10-25,NaN,15398,中国银行成都开发西区支行营业部,2014-01-22,9880100,2021-02-28,18889999,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
1372,B1,36010,中国银行德阳黄河新区支行,A2286,A0023,2017-11-27,9995802.0,36010,中国银行德阳黄河新区支行,2017-11-27,9958751,2021-02-28,495421999,100,100,100,100,100,100,100,0,100,100,100,100,100,100,100,100,100,100,100,N,1200
1493,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2018-01-18,7072612.0,36010,中国银行德阳黄河新区支行,2018-01-18,7072612,2021-02-28,499965367,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
2141,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-07-31,9881900.0,36010,中国银行德阳黄河新区支行,2019-07-31,9881900,2021-02-28,547599903,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
2222,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2018-01-18,7072612.0,36010,中国银行德阳黄河新区支行,2018-01-18,9881000,2021-02-28,499990792,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
2225,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2017-02-09,8452208.0,15075,中国银行德阳黄河东路支行,2017-02-11,7072612,2021-02-28,470539997,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
2588,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-09-07,9881900.0,36010,中国银行德阳黄河新区支行,2019-09-07,9881900,2021-02-28,551299982,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
2823,A3,36010,中国银行德阳黄河新区支行,A2286,A0023,2018-01-17,9881900.0,15009,中国银行天府新区华新中街支行,2018-01-17,9881900,2021-02-28,499927467,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
2993,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2008-07-11,NaN,15440,中国银行什邡支行营业部,2010-05-02,9881200,2021-02-28,19992558,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
3082,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2012-01-12,9995802.0,349,中国银行银行卡中心,2017-06-20,9881000,2021-02-28,277565999,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
3308,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-02-17,9881900.0,36010,中国银行德阳黄河新区支行,2019-02-17,9997751,2021-02-28,532999945,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
3544,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2012-05-25,9995802.0,349,中国银行银行卡中心,2017-05-02,7853379,2021-02-28,292659995,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
3731,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2018-05-22,7072612.0,36010,中国银行德阳黄河新区支行,2018-05-22,9881000,2021-02-28,509992303,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
3824,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2010-02-27,NaN,15087,中国银行德阳凯江路支行,2015-11-12,9881900,2021-02-28,21059998,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
4019,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2017-09-29,6422733.0,36010,中国银行德阳黄河新区支行,2017-10-01,9881000,2021-02-28,490629998,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
4195,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2018-05-28,376171.0,36010,中国银行德阳黄河新区支行,2018-05-28,9881000,2021-02-28,510403999,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
4599,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2018-02-26,7072612.0,36010,中国银行德阳黄河新区支行,2018-02-26,9881900,2021-02-28,502999114,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
4722,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2008-07-13,NaN,15439,中国银行绵竹支行营业部,2010-05-02,8900834,2021-02-28,19998086,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
4848,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2016-10-12,6619786.0,35922,中国银行德阳峨眉山南路支行,2017-05-25,9880100,2021-02-28,459069990,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
4988,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2010-10-08,3618196.0,15077,中国银行什邡金河路支行,2010-10-08,9881900,2021-02-28,103199977,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
5236,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2018-07-22,630094.0,36010,中国银行德阳黄河新区支行,2018-07-22,9881000,2021-02-28,514699967,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
5634,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2018-07-10,9881900.0,36010,中国银行德阳黄河新区支行,2018-07-10,9881000,2021-02-28,513649990,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
5697,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2009-11-12,NaN,15391,中国银行成都金牛支行营业部,2015-03-24,7072612,2021-02-28,18999126,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
5702,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2017-04-18,8395067.0,36010,中国银行德阳黄河新区支行,2017-05-22,9881000,2021-02-28,476855999,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
6022,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2008-12-24,NaN,15055,中国银行德阳泰山北路支行,2017-06-22,9881900,2021-02-28,19995358,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
6088,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2017-08-31,8395067.0,36010,中国银行德阳黄河新区支行,2017-09-13,9881200,2021-02-28,487909996,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
6142,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2015-06-13,8652692.0,15061,中国银行德阳旌湖支行,2017-07-12,9881900,2021-02-28,414039990,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
6437,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-03-25,7072612.0,36010,中国银行德阳黄河新区支行,2019-03-25,7072612,2021-02-28,536469995,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200
6667,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2013-12-12,6944487.0,15075,中国银行德阳黄河东路支行,2017-05-17,9880100,2021-02-28,355999098,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200

### 数据分组

In [60]:
df['月收入'].unique()

array([100,   1])

In [61]:
#可以通过pd.cut函数对列（金额，销量等）进行数据分组

bins = [0, 20, 40, 60, 80, 100]   #创建的bins用来接收以怎样的间隔分段
group_names = ['A','B','C','D','E'] #创建的group_names用来接收每段的取名
df['月收入分组']  = pd.cut(df['月收入'], bins, labels = group_names) #创建的新列‘月收入分组’记录分组结果

### 聚合函数

In [62]:
#count函数用以计数

df[df['创建机构名称'] == '中国银行德阳泰山北路支行'].count()

分级结果          316
归属行号          316
归属行名          316
归属二级行行号       316
归属一级行行号       316
客户号创建日期       316
创建柜员          143
创建机构号         316
创建机构名称        316
最后维护日期        316
最后维护柜员        316
报表日期          316
客户号           316
姓名            316
性别            316
国籍            316
常住地址          316
联系电话          316
证件类型          316
证件号码          316
证件有效期         316
职业            316
民族            316
出生日期          316
工作单位名称        316
工作单位行业类型      316
月收入           316
证件地址          316
手机号           316
居民涉税标识        316
签证类型          316
签证日期          316
是否在ACIF系统     316
年收入           316
月收入分组         316
dtype: int64

In [63]:
#多条件计数

df[(df['分级结果'].map(lambda x: x.startswith('A1'))) & (df['创建机构名称'] == '中国银行德阳泰山北路支行')].count()

分级结果          277
归属行号          277
归属行名          277
归属二级行行号       277
归属一级行行号       277
客户号创建日期       277
创建柜员          127
创建机构号         277
创建机构名称        277
最后维护日期        277
最后维护柜员        277
报表日期          277
客户号           277
姓名            277
性别            277
国籍            277
常住地址          277
联系电话          277
证件类型          277
证件号码          277
证件有效期         277
职业            277
民族            277
出生日期          277
工作单位名称        277
工作单位行业类型      277
月收入           277
证件地址          277
手机号           277
居民涉税标识        277
签证类型          277
签证日期          277
是否在ACIF系统     277
年收入           277
月收入分组         277
dtype: int64

In [64]:
df['分级结果'].map(lambda x: x.startswith('A1'))

0       False
1        True
2        True
3        True
4        True
        ...
6766     True
6767     True
6768     True
6769     True
6770     True
Name: 分级结果, Length: 6771, dtype: bool

In [65]:
#sum函数用于求和

df[(df['分级结果'].map(lambda x: x.startswith('A1'))) & (df['创建机构名称'] == '中国银行德阳泰山北路支行')].sum()

分级结果                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1
归属行号                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               9974770
归属行名          中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行中国银行德阳黄河新区支行
归属二级行行号                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286A2286
归属一级行行号                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023A0023

In [66]:
#mean函数用于求平均

df[(df['分级结果'].map(lambda x: x.startswith('A1'))) & (df['创建机构名称'] == '中国银行德阳泰山北路支行')].mean()

<ipython-input-66-f3e84f207b33>:3: FutureWarning: DataFrame.mean and DataFrame.median with numeric_only=None will include datetime64 and datetime64tz columns in a future version.
  df[(df['分级结果'].map(lambda x: x.startswith('A1'))) & (df['创建机构名称'] == '中国银行德阳泰山北路支行')].mean()

归属行号        3.601000e+04
创建柜员        4.962902e+06
创建机构号       1.505500e+04
最后维护柜员      8.098033e+06
姓名          1.000000e+02
性别          1.000000e+02
国籍          1.000000e+02
常住地址        1.000000e+02
联系电话        1.000000e+02
证件类型        1.000000e+02
证件号码        1.000000e+02
证件有效期       1.000000e+02
职业          1.000000e+02
民族          1.000000e+02
出生日期        1.000000e+02
工作单位名称      1.000000e+02
工作单位行业类型    1.000000e+02
月收入         1.000000e+02
证件地址        1.000000e+02
手机号         1.000000e+02
居民涉税标识      1.000000e+02
签证类型        1.000000e+02
签证日期        1.000000e+02
年收入         1.200000e+03
dtype: float64

In [67]:
#max函数用于最大值

df[(df['分级结果'].map(lambda x: x.startswith('A1'))) & (df['创建机构名称'] == '中国银行德阳泰山北路支行')].max()

分级结果                           A1
归属行号                        36010
归属行名                 中国银行德阳黄河新区支行
归属二级行行号                     A2286
归属一级行行号                     A0023
客户号创建日期       2019-12-04 00:00:00
创建柜员                    9995802.0
创建机构号                       15055
创建机构名称               中国银行德阳泰山北路支行
最后维护日期        2019-12-04 00:00:00
最后维护柜员                    9997773
报表日期          2021-02-28 00:00:00
客户号                      80632958
姓名                            100
性别                            100
国籍                            100
常住地址                          100
联系电话                          100
证件类型                          100
证件号码                          100
证件有效期                         100
职业                            100
民族                            100
出生日期                          100
工作单位名称                        100
工作单位行业类型                      100
月收入                           100
证件地址                          100
手机号                           100
居民涉税标识                        100
签证类型                          100
签证日期                          100
是否在ACIF系统                      N
年收入                          1200
月收入分组                           E
dtype: object

In [68]:
#min函数用于最小值

df[(df['分级结果'].map(lambda x: x.startswith('A1'))) & (df['创建机构名称'] == '中国银行德阳泰山北路支行')].min()

分级结果                           A1
归属行号                        36010
归属行名                 中国银行德阳黄河新区支行
归属二级行行号                     A2286
归属一级行行号                     A0023
客户号创建日期       2002-05-24 00:00:00
创建柜员                     208726.0
创建机构号                       15055
创建机构名称               中国银行德阳泰山北路支行
最后维护日期        2010-05-02 00:00:00
最后维护柜员                      87505
报表日期          2021-02-28 00:00:00
客户号                     104462713
姓名                            100
性别                            100
国籍                            100
常住地址                          100
联系电话                          100
证件类型                          100
证件号码                          100
证件有效期                         100
职业                            100
民族                            100
出生日期                          100
工作单位名称                        100
工作单位行业类型                      100
月收入                           100
证件地址                          100
手机号                           100
居民涉税标识                        100
签证类型                          100
签证日期                          100
是否在ACIF系统                      N
年收入                          1200
月收入分组                           E
dtype: object

### 分类汇总

In [69]:
#groupby函数实现分组统计

df_cs = df.groupby(['分级结果','归属行名'])['客户号'].count().reset_index(name = '总计')
df_cs

  分级结果          归属行名    总计
0   A1  中国银行德阳黄河新区支行  5583
1   A2  中国银行德阳黄河新区支行    67
2   A3  中国银行德阳黄河新区支行   904
3   A4  中国银行德阳黄河新区支行     9
4   B1  中国银行德阳黄河新区支行    36
5   B2  中国银行德阳黄河新区支行     3
6   B3  中国银行德阳黄河新区支行     2
7   B4  中国银行德阳黄河新区支行     4
8   B5  中国银行德阳黄河新区支行    15
9    C  中国银行德阳黄河新区支行   148

In [70]:
df_cs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   分级结果    10 non-null     object
 1   归属行名    10 non-null     object
 2   总计      10 non-null     int64
dtypes: int64(1), object(2)
memory usage: 368.0+ bytes

In [71]:
#添加条件筛选(可以通过&或者|组合条件)

df_cs.query("总计 > 500 | 总计 < 10")

  分级结果          归属行名    总计
0   A1  中国银行德阳黄河新区支行  5583
2   A3  中国银行德阳黄河新区支行   904
3   A4  中国银行德阳黄河新区支行     9
5   B2  中国银行德阳黄河新区支行     3
6   B3  中国银行德阳黄河新区支行     2
7   B4  中国银行德阳黄河新区支行     4

In [72]:
df_cs[(df_cs['总计']>500) | (df_cs['总计']<10)]

  分级结果          归属行名    总计
0   A1  中国银行德阳黄河新区支行  5583
2   A3  中国银行德阳黄河新区支行   904
3   A4  中国银行德阳黄河新区支行     9
5   B2  中国银行德阳黄河新区支行     3
6   B3  中国银行德阳黄河新区支行     2
7   B4  中国银行德阳黄河新区支行     4

In [73]:
#如果多列才能确定一个分组

df['手机号'] = df['手机号'].astype('str') #手机号初始是整数形式，需要转为字符型
cellphone = ['0','100','1']
df[df['手机号'].isin(cellphone)].groupby(['手机号','归属行名'])['客户号'].count().reset_index(name = '客户数')

   手机号          归属行名   客户数
0    0  中国银行德阳黄河新区支行    74
1    1  中国银行德阳黄河新区支行     1
2  100  中国银行德阳黄河新区支行  6696

In [74]:
df[df['手机号'].isin(cellphone)]

,分级结果,归属行号,归属行名,归属二级行行号,归属一级行行号,客户号创建日期,创建柜员,创建机构号,创建机构名称,最后维护日期,最后维护柜员,报表日期,客户号,姓名,性别,国籍,常住地址,联系电话,证件类型,证件号码,证件有效期,职业,民族,出生日期,工作单位名称,工作单位行业类型,月收入,证件地址,手机号,居民涉税标识,签证类型,签证日期,是否在ACIF系统,年收入,月收入分组
0,A3,36010,中国银行德阳黄河新区支行,A2286,A0023,2011-11-18,234777.0,15055,中国银行德阳泰山北路支行,2017-07-22,9880100,2021-02-28,271251702,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200,E
1,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2018-08-14,9881900.0,36010,中国银行德阳黄河新区支行,2018-08-14,9881000,2021-02-28,516976310,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200,E
2,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2014-11-13,5366735.0,35922,中国银行德阳峨眉山南路支行,2016-11-15,9881900,2021-02-28,391831475,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200,E
3,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2012-04-10,5656324.0,15062,中国银行德阳庐山南路支行,2015-11-16,9881000,2021-02-28,288367680,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200,E
4,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-05-10,7072612.0,36010,中国银行德阳黄河新区支行,2019-05-10,7072612,2021-02-28,540339484,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200,E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6766,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-01-10,9881900.0,36010,中国银行德阳黄河新区支行,2019-01-10,9881900,2021-02-28,530409314,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200,E
6767,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2017-12-07,6422733.0,36010,中国银行德阳黄河新区支行,2017-12-07,6422733,2021-02-28,496339576,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200,E
6768,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-03-25,9881200.0,15442,中国银行德阳罗江支行营业部,2019-03-25,9881900,2021-02-28,536412969,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200,E
6769,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-04-26,9881900.0,36010,中国银行德阳黄河新区支行,2019-04-26,9958750,2021-02-28,539321779,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200,E
6770,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2016-08-08,438782.0,35922,中国银行德阳峨眉山南路支行,2017-07-25,9958750,2021-02-28,453369765,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200,E

# 数据预处理

### 数据表合并

In [75]:
#表拼接（上下纵向拼接使行变多）

df2 = pd.read_csv(r'/Users/kevin/Documents/财管部需求/邛崃支行瑞云欣广场支行.csv'
                 ,encoding = 'GBK'
              #  ,skiprows = 1
              #   ,header = None
                 )
df3 = pd.read_csv(r'/Users/kevin/Documents/财管部需求/锦江支行海椒市支行.csv'
                 ,encoding = 'GBK')

In [76]:
df2

,分级结果,归属行号,归属行名,归属二级行行号,归属一级行行号,客户号创建日期,创建柜员,创建机构号,创建机构名称,最后维护日期,最后维护柜员,报表日期,客户号,姓名,性别,国籍,常住地址,联系电话,证件类型,证件号码,证件有效期,职业,民族,出生日期,工作单位名称,工作单位行业类型,月收入,证件地址,手机号,居民涉税标识,签证类型,签证日期,是否在ACIF系统
0,A1,14935,中国银行邛崃瑞云欣广场支行,A1127,A0023,2009-04-13,NaN,15385,中国银行邛崃支行营业部,2017-07-17,6241615,2021-02-28,21921382,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
1,A1,14935,中国银行邛崃瑞云欣广场支行,A1127,A0023,2012-04-28,316752.0,14935,中国银行邛崃瑞云欣广场支行,2012-04-28,9880100,2021-02-28,290139079,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
2,A3,14935,中国银行邛崃瑞云欣广场支行,A1127,A0023,2013-10-16,2129871.0,14935,中国银行邛崃瑞云欣广场支行,2013-10-16,8352946,2021-02-28,347843287,100,100,100,100,100,100,100,100,100,100,100,1,100,100,100,100,100,100,100,N
3,B1,14935,中国银行邛崃瑞云欣广场支行,A1127,A0023,2009-11-15,NaN,14935,中国银行邛崃瑞云欣广场支行,2010-05-02,0,2021-02-28,19022280,100,100,100,1,100,100,100,0,0,0,100,0,100,1,0,0,100,100,100,N
4,A3,14935,中国银行邛崃瑞云欣广场支行,A1127,A0023,2005-08-31,NaN,15370,中国银行四川省分行支付清算部,2016-05-17,9881900,2021-02-28,30534114,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24850,A1,14935,中国银行邛崃瑞云欣广场支行,A1127,A0023,2017-12-10,8352946.0,14935,中国银行邛崃瑞云欣广场支行,2017-12-10,9881000,2021-02-28,496591182,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
24851,C,14935,中国银行邛崃瑞云欣广场支行,A1127,A0023,2014-05-18,316752.0,14935,中国银行邛崃瑞云欣广场支行,2016-05-20,316752,2021-02-28,374446086,100,100,100,100,100,0,100,100,0,0,100,0,100,100,0,100,100,100,100,Y
24852,A1,14935,中国银行邛崃瑞云欣广场支行,A1127,A0023,2019-11-24,9881900.0,14935,中国银行邛崃瑞云欣广场支行,2019-11-24,9881900,2021-02-28,557978815,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
24853,A1,14935,中国银行邛崃瑞云欣广场支行,A1127,A0023,2016-03-29,6449328.0,14935,中国银行邛崃瑞云欣广场支行,2016-03-31,5745944,2021-02-28,442554937,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N
24854,A1,14935,中国银行邛崃瑞云欣广场支行,A1127,A0023,2019-03-15,9881900.0,14935,中国银行邛崃瑞云欣广场支行,2019-03-15,9881900,2021-02-28,535555952,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N

In [77]:
#可以使用pd.concat实现表的纵向拼接

df_new = pd.concat([df, df2, df3]
                  ,axis = 0   #axis = 0表示纵向拼接， 适用于表结构相同的多张表
                  )

df_new

,分级结果,归属行号,归属行名,归属二级行行号,归属一级行行号,客户号创建日期,创建柜员,创建机构号,创建机构名称,最后维护日期,最后维护柜员,报表日期,客户号,姓名,性别,国籍,常住地址,联系电话,证件类型,证件号码,证件有效期,职业,民族,出生日期,工作单位名称,工作单位行业类型,月收入,证件地址,手机号,居民涉税标识,签证类型,签证日期,是否在ACIF系统,年收入,月收入分组
0,A3,36010,中国银行德阳黄河新区支行,A2286,A0023,2011-11-18 00:00:00,234777.0,15055,中国银行德阳泰山北路支行,2017-07-22 00:00:00,9880100,2021-02-28 00:00:00,271251702,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200.0,E
1,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2018-08-14 00:00:00,9881900.0,36010,中国银行德阳黄河新区支行,2018-08-14 00:00:00,9881000,2021-02-28 00:00:00,516976310,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200.0,E
2,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2014-11-13 00:00:00,5366735.0,35922,中国银行德阳峨眉山南路支行,2016-11-15 00:00:00,9881900,2021-02-28 00:00:00,391831475,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200.0,E
3,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2012-04-10 00:00:00,5656324.0,15062,中国银行德阳庐山南路支行,2015-11-16 00:00:00,9881000,2021-02-28 00:00:00,288367680,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200.0,E
4,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-05-10 00:00:00,7072612.0,36010,中国银行德阳黄河新区支行,2019-05-10 00:00:00,7072612,2021-02-28 00:00:00,540339484,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200.0,E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39419,A3,14939,中国银行成都海椒市支行,B1024,A0023,2015-02-16,3656826.0,15154,中国银行南充镇江西路支行,2017-02-17,9881000,2021-02-28,403477105,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,NaN,NaN
39420,A3,14939,中国银行成都海椒市支行,B1024,A0023,2011-10-09,6620860.0,14939,中国银行成都海椒市支行,2016-12-30,1316215,2021-02-28,264981353,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,NaN,NaN
39421,A1,14939,中国银行成都海椒市支行,B1024,A0023,2015-12-11,6011533.0,15398,中国银行成都开发西区支行营业部,2017-05-11,9881900,2021-02-28,433562884,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,NaN,NaN
39422,A3,14939,中国银行成都海椒市支行,B1024,A0023,2007-05-04,NaN,14939,中国银行成都海椒市支行,2016-11-27,9881900,2021-02-28,23266061,100,100,100,100,100,100,100,100,100,100,100,1,100,100,100,100,100,100,100,N,NaN,NaN
39423,B5,14939,中国银行成都海椒市支行,B1024,A0023,2005-03-10,NaN,14939,中国银行成都海椒市支行,2010-05-02,0,2021-02-28,22163499,100,100,100,1,100,100,1,100,0,0,100,0,100,1,0,0,100,100,100,Y,NaN,NaN

In [78]:
#append函数也可以实现相同的效果

df_new = df.append([df2,df3])
df_new

,分级结果,归属行号,归属行名,归属二级行行号,归属一级行行号,客户号创建日期,创建柜员,创建机构号,创建机构名称,最后维护日期,最后维护柜员,报表日期,客户号,姓名,性别,国籍,常住地址,联系电话,证件类型,证件号码,证件有效期,职业,民族,出生日期,工作单位名称,工作单位行业类型,月收入,证件地址,手机号,居民涉税标识,签证类型,签证日期,是否在ACIF系统,年收入,月收入分组
0,A3,36010,中国银行德阳黄河新区支行,A2286,A0023,2011-11-18 00:00:00,234777.0,15055,中国银行德阳泰山北路支行,2017-07-22 00:00:00,9880100,2021-02-28 00:00:00,271251702,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200.0,E
1,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2018-08-14 00:00:00,9881900.0,36010,中国银行德阳黄河新区支行,2018-08-14 00:00:00,9881000,2021-02-28 00:00:00,516976310,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200.0,E
2,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2014-11-13 00:00:00,5366735.0,35922,中国银行德阳峨眉山南路支行,2016-11-15 00:00:00,9881900,2021-02-28 00:00:00,391831475,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200.0,E
3,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2012-04-10 00:00:00,5656324.0,15062,中国银行德阳庐山南路支行,2015-11-16 00:00:00,9881000,2021-02-28 00:00:00,288367680,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200.0,E
4,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2019-05-10 00:00:00,7072612.0,36010,中国银行德阳黄河新区支行,2019-05-10 00:00:00,7072612,2021-02-28 00:00:00,540339484,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200.0,E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39419,A3,14939,中国银行成都海椒市支行,B1024,A0023,2015-02-16,3656826.0,15154,中国银行南充镇江西路支行,2017-02-17,9881000,2021-02-28,403477105,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,NaN,NaN
39420,A3,14939,中国银行成都海椒市支行,B1024,A0023,2011-10-09,6620860.0,14939,中国银行成都海椒市支行,2016-12-30,1316215,2021-02-28,264981353,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,NaN,NaN
39421,A1,14939,中国银行成都海椒市支行,B1024,A0023,2015-12-11,6011533.0,15398,中国银行成都开发西区支行营业部,2017-05-11,9881900,2021-02-28,433562884,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,NaN,NaN
39422,A3,14939,中国银行成都海椒市支行,B1024,A0023,2007-05-04,NaN,14939,中国银行成都海椒市支行,2016-11-27,9881900,2021-02-28,23266061,100,100,100,100,100,100,100,100,100,100,100,1,100,100,100,100,100,100,100,N,NaN,NaN
39423,B5,14939,中国银行成都海椒市支行,B1024,A0023,2005-03-10,NaN,14939,中国银行成都海椒市支行,2010-05-02,0,2021-02-28,22163499,100,100,100,1,100,100,1,100,0,0,100,0,100,1,0,0,100,100,100,Y,NaN,NaN

In [79]:
df_new['客户号'] = df_new['客户号'].astype(str)

In [80]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 71050 entries, 0 to 39423
Data columns (total 35 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   分级结果        71050 non-null  object
 1   归属行号        71050 non-null  int64
 2   归属行名        71050 non-null  object
 3   归属二级行行号     71050 non-null  object
 4   归属一级行行号     71050 non-null  object
 5   客户号创建日期     71050 non-null  object
 6   创建柜员        49167 non-null  float64
 7   创建机构号       71050 non-null  int64
 8   创建机构名称      71049 non-null  object
 9   最后维护日期      71050 non-null  object
 10  最后维护柜员      71050 non-null  int64
 11  报表日期        71050 non-null  object
 12  客户号         71050 non-null  object
 13  姓名          71050 non-null  int64
 14  性别          71050 non-null  int64
 15  国籍          71050 non-null  int64
 16  常住地址        71050 non-null  int64
 17  联系电话        71050 non-null  int64
 18  证件类型        71050 non-null  int64
 19  证件号码        71050 non-null  int64
 20  证件有效期       71050 non-null  int64
 21  职业          71050 non-null  int64
 22  民族          71050 non-null  int64
 23  出生日期        71050 non-null  int64
 24  工作单位名称      71050 non-null  int64
 25  工作单位行业类型    71050 non-null  int64
 26  月收入         71050 non-null  int64
 27  证件地址        71050 non-null  int64
 28  手机号         71050 non-null  object
 29  居民涉税标识      71050 non-null  int64
 30  签证类型        71050 non-null  int64
 31  签证日期        71050 non-null  int64
 32  是否在ACIF系统   71050 non-null  object
 33  年收入         6771 non-null   float64
 34  月收入分组       6771 non-null   object
dtypes: float64(2), int64(21), object(12)
memory usage: 19.5+ MB

### 替代Vlookup

In [81]:
#可以高效替代excel中的vlookup
#pd.merge可以实现数据表合并

teller = pd.DataFrame({'姓名':['唐三藏','孙悟空','猪八戒','白龙马','沙悟净'],
                       '柜员号':['9880100','9881000','9881900','7072612','6422733']
                      }
)
teller

    姓名      柜员号
0  唐三藏  9880100
1  孙悟空  9881000
2  猪八戒  9881900
3  白龙马  7072612
4  沙悟净  6422733

In [82]:
df['最后维护柜员'] = df['最后维护柜员'].astype('str')

vlookup = pd.merge(df, teller
                    ,how='right'
                    ,left_on = '最后维护柜员'
                    ,right_on = '柜员号'
                     )                    #how参数决定以何种方式进行合并，默认为inner
                                          #inner以交集方式合并
                                          #left以左表为主表合并右表数据，最终结果行数必定大于等于左表
                                          #right以右表为主表合并左表数据，最终结果行数必定大于等于右表
                                          #outer以并集方式合并

In [83]:
vlookup

,分级结果,归属行号,归属行名,归属二级行行号,归属一级行行号,客户号创建日期,创建柜员,创建机构号,创建机构名称,最后维护日期,最后维护柜员,报表日期,客户号,姓名_x,性别,国籍,常住地址,联系电话,证件类型,证件号码,证件有效期,职业,民族,出生日期,工作单位名称,工作单位行业类型,月收入,证件地址,手机号,居民涉税标识,签证类型,签证日期,是否在ACIF系统,年收入,月收入分组,姓名_y,柜员号
0,A3,36010,中国银行德阳黄河新区支行,A2286,A0023,2011-11-18,234777.0,15055,中国银行德阳泰山北路支行,2017-07-22,9880100,2021-02-28,271251702,100,100,100,1,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200,E,唐三藏,9880100
1,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2020-01-06,6819299.0,36010,中国银行德阳黄河新区支行,2020-01-06,9880100,2021-02-28,561493932,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200,E,唐三藏,9880100
2,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2010-12-30,9991600.0,15437,中国银行德阳分行营业部,2010-12-30,9880100,2021-02-28,108008221,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200,E,唐三藏,9880100
3,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2018-06-28,630094.0,36010,中国银行德阳黄河新区支行,2018-06-28,9880100,2021-02-28,512796908,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200,E,唐三藏,9880100
4,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2014-11-04,195840.0,35922,中国银行德阳峨眉山南路支行,2016-11-06,9880100,2021-02-28,390412225,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200,E,唐三藏,9880100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4979,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2009-11-25,NaN,15368,中国银行四川省分行营业部,2017-11-04,6422733,2021-02-28,17161379,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200,E,沙悟净,6422733
4980,C,36010,中国银行德阳黄河新区支行,A2286,A0023,2018-02-26,6422733.0,36010,中国银行德阳黄河新区支行,2018-02-26,6422733,2021-02-28,502955651,100,100,100,100,100,0,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200,E,沙悟净,6422733
4981,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2017-12-18,6422733.0,36010,中国银行德阳黄河新区支行,2017-12-18,6422733,2021-02-28,497294764,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200,E,沙悟净,6422733
4982,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2009-02-03,NaN,15370,中国银行四川省分行支付清算部,2017-10-31,6422733,2021-02-28,30664478,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200,E,沙悟净,6422733
4983,A1,36010,中国银行德阳黄河新区支行,A2286,A0023,2017-12-07,6422733.0,36010,中国银行德阳黄河新区支行,2017-12-07,6422733,2021-02-28,496339576,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,N,1200,E,沙悟净,6422733

# 数据透视表

<img src="./数据透视表参数.jpg" style="zoom:80%" />

In [84]:
#pd.pivot_table函数可以获得数据透视表

mps = pd.pivot_table(df_new
               ,index= ['归属行名','手机号']
               ,values = ['客户号']
               ,aggfunc = ['count'] #替代方式len，np.count_nonzero（非零计数） 
               ,fill_value = 0
               ,margins = True
               ,margins_name = '总计'    
              ).reset_index ()
mps

            归属行名  手机号  count
                         客户号
0   中国银行德阳黄河新区支行    0     74
1   中国银行德阳黄河新区支行    1      1
2   中国银行德阳黄河新区支行  100   6696
3    中国银行成都海椒市支行    0   6257
4    中国银行成都海椒市支行    1    778
5    中国银行成都海椒市支行  100  32389
6  中国银行邛崃瑞云欣广场支行    0   3211
7  中国银行邛崃瑞云欣广场支行    1    422
8  中国银行邛崃瑞云欣广场支行  100  21222
9             总计       71050

In [85]:
mps_new = pd.pivot_table(df_new
               ,index= ['归属行名','手机号']
               ,values = ['客户号','月收入']
               ,aggfunc = {'客户号':'count', '月收入':'sum'}
               ,fill_value = 0
               ,margins = True
               ,margins_name = '总计'    
              )
mps_new

                     客户号      月收入
归属行名          手机号
中国银行德阳黄河新区支行  0       74     7004
              1        1      100
              100   6696   669105
中国银行成都海椒市支行   0     6257   211484
              1      778    41962
              100  32389  2980015
中国银行邛崃瑞云欣广场支行 0     3211    94588
              1      422    22103
              100  21222  1997262
总计                 71050  6023623

In [86]:
cs = pd.pivot_table(df_new
               ,index= ['归属行名','创建机构名称','分级结果']
               ,values = ['客户号']
               ,aggfunc = 'count' #替代方式len，np.count_nonzero（非零计数） 
               ,fill_value = 0
               ,margins = True
               ,margins_name = '总计'    
               )
cs

                                       客户号
归属行名          创建机构名称           分级结果
中国银行德阳黄河新区支行  中国银行三台喜洋洋广场支行    A1        1
              中国银行三台支行营业部      A3        1
              中国银行三台樟树路支行      A1        1
              中国银行三台老西街支行      A1        1
              中国银行三明东五支行       A1        2
...                                    ...
中国银行邛崃瑞云欣广场支行 中国银行鹤岗分行营业部      A3        1
              中国银行鹰潭市环城东路支行    A1        1
              中国银行龙南支行营业部      A1        1
              四川误用责任中心20140624 A1        1
总计                                   71049

[4475 rows x 1 columns]

In [87]:
#增加百分比

cs['所占本行百分比'] = (cs['客户号']/cs.groupby(['归属行名','创建机构名称'])['客户号'].sum()*100).astype(str)+'%'
cs = cs.reset_index()
cs

               归属行名            创建机构名称 分级结果    客户号 所占本行百分比
0      中国银行德阳黄河新区支行     中国银行三台喜洋洋广场支行   A1      1  100.0%
1      中国银行德阳黄河新区支行       中国银行三台支行营业部   A3      1  100.0%
2      中国银行德阳黄河新区支行       中国银行三台樟树路支行   A1      1  100.0%
3      中国银行德阳黄河新区支行       中国银行三台老西街支行   A1      1  100.0%
4      中国银行德阳黄河新区支行        中国银行三明东五支行   A1      2  100.0%
...             ...               ...  ...    ...     ...
4470  中国银行邛崃瑞云欣广场支行       中国银行鹤岗分行营业部   A3      1  100.0%
4471  中国银行邛崃瑞云欣广场支行     中国银行鹰潭市环城东路支行   A1      1  100.0%
4472  中国银行邛崃瑞云欣广场支行       中国银行龙南支行营业部   A1      1  100.0%
4473  中国银行邛崃瑞云欣广场支行  四川误用责任中心20140624   A1      1  100.0%
4474             总计                         71049  100.0%

[4475 rows x 5 columns]

# 数据输出

### 写为excel文件

In [99]:
#to_excel函数可以输出EXCEL格式文件，sheet_name参数指定工作页名

cs.to_excel('各行分级结果汇总.xlsx',excel_writer = r'/Users/kevin/Desktop',sheet_name='汇总情况')

TypeError: to_excel() got multiple values for argument 'excel_writer'

### 写为CSV文件

In [89]:
#to_csv函数写为CSV格式文件

cs.to_csv('分级结果.csv')